Seagate/cortx-utils

c-utils/src/common/CMakeLists.txt
c-utils/src/common/perfc.c
c-utils/src/cortx/m0common.c
c-utils/src/cortx/m0kvs.c
c-utils/src/include/operation.h
c-utils/src/include/perf/perf-counters.h
c-utils/src/test/perf/perf-manual-test.c

Introduce new performance counters and action maps as described in EOS-13398 and in the HLD's appendix section and update unit test
commit 0afb4d0ac4f683b209584c0cdd26cabba715aa4d
Date:   Tue Sep 22 17:05:44 2020 -0600
EOS-13398: Re-structure Cortx-FS perfr counters format - v2
List of added/modified/deleted files:
modified:   c-utils/src/common/CMakeLists.txt
new file:   c-utils/src/common/perfc.c
modified:   c-utils/src/cortx/m0common.c
modified:   c-utils/src/cortx/m0kvs.c
modified:   c-utils/src/include/operation.h
modified:   c-utils/src/include/perf/perf-counters.h
modified:   c-utils/src/test/perf/perf-manual-test.c
Introduce new performance counters …

EOS-13398: Re-structure Cortx-FS perfr counters format - v2

---

c-utils/src/include/perf/perf-counters.h

Introduce new TLS based performance counters and associated APIs as described in EOS-13398 and in the HLD's appendix section
commit d58cd8336170d215cdc7303d07fb60a0d7555968
Date:   Wed Sep 23 03:43:41 2020 -0600
EOS-12314: [Spike] Design TLS-based context propagation for Operation API
List of added/modified/deleted files:
modified:   c-utils/src/include/perf/perf-counters.h
modified:   c-utils/src/common/perfc.c
modified:   c-utils/src/include/operation.h
Introduce new TLS based performance counters and associated APIs as described in EOS-13398 and in the HLD's appendix section
Unit test (on LABVM):
Compile and run UT with and without …

EOS-12314: [Spike] Design TLS-based context propagation for Operation API

---

c-utils/src/common/perfc.c
c-utils/src/include/perf/perf-counters.h
c-utils/src/test/perf/perf-manual-test.c

commit d3ebfc398554cf556220f9deb8fec60ee3e0d8b7
Date:   Tue Sep 29 02:12:50 2020 -0600
EOS-8896: NFS ADDB: NFS-only tracepoints for READ (repo utils)
List of modified files:
modified:   c-utils/src/common/perfc.c
modified:   c-utils/src/include/perf/perf-counters.h
modified:   c-utils/src/test/perf/perf-manual-test.c
Add new performance counters and integrate them further with other modules using newly added APIs
Addb APIs integration for read path
Unit test:
Compilation with and without ENABLE_TSDB_ADDB flag
Addb unit test while integrated with read handler
Regular UTs (both with and without ENABLE_TSDB_ADDB flag)
addb dump o/p from read handler after …

EOS-8896: NFS ADDB: NFS-only tracepoints for READ (repo utils)

---

c-utils/src/CMakeLists.txt
c-utils/src/addb/CMakeLists.txt
c-utils/src/addb/plugin.c

**Problem Statement**
EOS-8947: Decoder for ADDB logs
**Problem Description**
Implement the decoder for the ADDB logs
**Solution Overview**
- Create a plugin for decoder plugin.c 
- Implement the m0_addb2_load_interps() method which is exposed by motr dump.
- Decode the following kind
- State 
- Attribute
- Map
**Unit Test Cases**
`
**sudo m0addb2dump -p /usr/lib64/libcortx-utils.so -- /addb_27527/o/100000000000000\:2 | grep fsuser** 
* 2020-09-29-17:27:47.484505618 fsuser_state     fsal_read,  state,      5035,       init
* 2020-09-29-17:27:47.484506598 fsuser_attribute fsal_read,  attribute,  5035,       read_offset, ?               0?
* 2020-09-29-17:27:47.484507284 fsuser_attribute fsal_read,  attribute,  5035,       read_vector_count, ?               1?
* …

EOS-8947: Decoder for ADDB logs

---

py-utils/docs/ha/ha_script/pcs.sh.sample
py-utils/src/utils/ha/hac/generate.py

<pre>
Cannot change pcs command line parameter master to primary
</pre>
<pre>
Not done
</pre>
<pre>
Found problem in review, https://github.com/Seagate/cortx-py-utils/commit/c85243149959178189bb7a681c4b812497e64e8c#r42512233
</pre>
<pre>
Reverted pcs parameter back to master which was changed to primary.
</pre>
<pre>
NA
</pre>
Signed-off-by: Naval Patel <naval.patel@seagate.com>

[Main] EOS-13013 reverted primary to master in py-utils

---

py-utils/src/utils/addb/__init__.py
py-utils/src/utils/addb/addb2db_cortxfs.py

commit 8a96b6ef51123e771030e9c7cd8acf80c65998e0
Date:   Sun Oct 4 15:40:30 2020 -0600
EOS-13787:[Enabler] NFS ADDB: Explore and implement add2db.py for NFS
List of modified files:
new file:   addb2db_nfs.py
Add python script to read and convert the text performance dump to sql database file for NFS
Unit test:
Based on EOS-8947, using the new script, read the filtered text dump file containing the new
nfs-cortxfs performance counters (state, map and attribute) and create a sql3 database file.
Verify the sql3 database file is ok.
test O/P:
cd /home/751521/EOS-13787
m0addb2dump -p /usr/lib64/libcortx-utils.so -- /$(ls -t addb* | head -n 1 | sed …

EOS-13787:[Enabler] NFS ADDB: Explore and implement add2db.py for NFS

---

c-utils/src/addb/plugin.c
c-utils/src/include/perf/perf-counters.h
c-utils/src/test/perf/perf-manual-test.c

commit 65c25247aef3e380d092441a87647894ebdf773e
Date:   Mon Oct 12 17:23:50 2020 -0600
EOS-13985:Implement nfs_req.py and hist.py <Part 1, utils repo>
List of modified files:
modified:   c-utils/src/addb/plugin.c
modified:   c-utils/src/include/perf/perf-counters.h
modified:   c-utils/src/test/perf/perf-manual-test.c
This repo's change is to track the operation id of immediate callers in map performance counters which will be used by addb2db_cortxfs.py. Thi
Unit test:
Run NFS READ IO test, generate DB from addb2db_cortxfs.py, use that DB to generate a png file which shows call graph constructed from that
TODO: Implement timeline and histogram tools
The …

EOS-13985:Implement nfs_req.py and hist.py <utils repo>

---

py-utils/README.md
py-utils/requirements.txt
py-utils/setup.py
py-utils/utils-post-install
py-utils/utils-pre-uninstall

Following packages are required by cortx-py-utils but are not installed as part of
the rpm installation. Components using cortx-py-utils fail due to these
dependencies and require to handle them separately.
```
aiohttp==3.6.1
elasticsearch-dsl==6.4.0
python-consul==1.1.0
schematics==2.1.0
toml==0.10.0
```
Solutions:
- Add  a post install script to install the dependencies.
This script can be specified to setup.py bdist_rpm command
as follows,
```
python3.6 setup.py bdist_rpm --post-install utils-post-install
```
Built rpm can then be installed along with dependencies,
```
[root@ssc-vm-c-0552 py-utils]# rpm -ivh dist/cortx-py-utils-1.0.0-1.noarch.rpm
Preparing...                          ################################# [100%]
Updating / installing...
1:cortx-py-utils-1.0.0-1 …
```

EOS-14340: cortx-py-utils rpm installation does not install dependencies

---

py-utils/utils-post-install
py-utils/utils-pre-uninstall

As part of the cortx-py-utils installation its related python dependencies are
installed as well. These dependencies are presently installed using command
`python -m pip install -r requirements.txt` but using `python` requires python-devel
package during installation to build setup.py for one of the modules `yarl`.
python-devel being not present as part of the overall product installation,
cortx-py-utils installation fails.
Solution:
This dependency on python-devel can be avoided by not using `python -m` but
directly using `pip3.6 install -r requirements.txt` to install required python
modules.
Signed-off-by: Mandar Sawant <mandar.sawant@seagate.com>

Problem: cortx-py-utils installation fails

---

.github/stale.yml
.github/workflows/triage.yml

Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@seagate.com>
Triage is an important part of open source. It can be difficult to keep up with the issues as the size of a project grows, the demands placed on the maintainers grow. This means they are forced to choose between spending enormous amounts of time reviewing each GitHub issue, only skimming over issues, or worse, ignoring issues.
Triage action can help an open-source project by labeling newly opened issues as `needs-triage`. So, maintainers could easily filter out all unattended/missed issues and label them appropriately in triage meetings. Now, it would be easy for a specific group of maintainers to filter out issues of their expertise/interest and start reviewing it in a timely manner.

[GitHub Action] Issue triage

---

c-utils/src/include/perf/perf-counters.h
c-utils/src/test/perf/perf-manual-test.c

[root@ssc-vm-c-0040 /]# ./cortx-posix/scripts/test.sh
--
--
Configuration Completed
Clean indexes prepared
NSAL Unit tests
NS Tests
Test results are logged to /var/log/cortx/test/ut/ut_nsal.log
Total tests  = 5
Tests passed = 5
Tests failed = 0
Iterator test
Test results are logged to /var/log/cortx/test/ut/ut_nsal.log
Total tests  = 2
Tests passed = 2
Tests failed = 0
KVTree test
Test results are logged to /var/log/cortx/test/ut/ut_nsal.log
Total tests  = 17
Tests passed = 17
Tests failed = 0
Global KVS Tests
Test results are logged to /var/log/cortx/test/ut/ut_nsal.log
Total tests  = 4
Tests passed = 4
Tests failed = 0
CORTXFS Unit tests
Endpoint ops Tests
Test results are logged to /var/log/cortx/test/ut/ut_cortxfs.logs
Total …

EOS-13996:ADDB:Profiling for all I/O operations (utils repo)

---

statsd-utils/statsd-elasticsearch-backend-0.4.2/lib/elasticsearch.js

<pre>
<code>
Elasticsearch statsd connection fails
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
req = http.request(reqOpts, function (res) { });
Here, request error not handled causing Elasticsearch to restart.
</code>
</pre>
<pre>
<code>
req = http.request(reqOpts, function (res) { });
Handled error for connection request
</code>
</pre>
<pre>
<code>
Tested on vm with es - statsd connecton.
</code>
</pre>

stats_connection_fix: Fix http request issue

---

py-utils/requirements.txt
py-utils/src/utils/ssh.py

[root@smc5-m11 utils]# **python3 -m unittest -v cortx/test/test_ssh_connection.py**
test_command_execution_ok (cortx.test.test_ssh_connection.TestSSHChannel)
Check if command is executed successfully ... Creating mailbox file: File exists
ok
test_connection_ok (cortx.test.test_ssh_connection.TestSSHChannel)
Check if ssh connection is alive ... Creating mailbox file: File exists
ok
test_reconnect_ok (cortx.test.test_ssh_connection.TestSSHChannel)
Check ssh re-connect after disconnection caller ... Creating mailbox file: File exists
ok
test_recv_file (cortx.test.test_ssh_connection.TestSSHChannel) ... Creating mailbox file: File exists
ok
test_send_file (cortx.test.test_ssh_connection.TestSSHChannel) ... Creating mailbox file: File exists
ok …

EOS-15347: Removing debug log level and adding required paramiko version

---

statsd-utils/jenkins/stats_utils.spec

Updated the license from "Seagate Proprietary" to "Seagate"
Signed-off-by: Sachin Punadikar <sachin.punadikar@seagate.com>

Fix license for stats-utils

---

py-utils/src/utils/kv_store/kv_store_collection.py

Facing an Issue with Cortx-py-utils Conf file.
While saving csm.conf file the nested values in csm.conf are not saved correctly.
For e.g
```
MAINTENANCE:
shutdown_cron_time: "120"
```
is saved as 
```
MAINTENANCE: {shutdown_cron_time: '120'}
```
Above Error is since cortx-py-utils uses PyYaml to save YAML files.
However while using dump method in YAML file a key knows as  default_flow_style is not passed as false.
default_flow_style is used to serailize all the data in YAML. And hence the Reason the code is not correctly csm.conf.

EOS-16723 Changes for Fixing Yaml Saving in Cortx-Py-Utils.

---

py-utils/README.md
py-utils/src/utils/validator/commands.py
py-utils/src/utils/validator/v_pkg.py
py-utils/src/utils/validator/v_service.py
py-utils/src/utils/validator/validate.py
py-utils/test/validator/test_pkg_validator.py
py-utils/test/validator/test_service_validator.py

commit 125555be232337ef9c2ebac20d26ad26c158b69c
Date:   Wed Jan 20 08:36:43 2021 -0700
EOS-16423: S3 Mini-provisioner: Validations in post_install
Add new validator APIs to check if services are running and if rpm or pip3 packages are installed on local or remote host
Files edited/added:
modified:   src/utils/validator/commands.py
new file:   src/utils/validator/v_pkg.py
new file:   src/utils/validator/v_service.py
modified:   src/utils/validator/validate.py
new file:   test/validator/test_pkg_validator.py
new file:   test/validator/test_service_validator.py
Testing done:
Used newly created unit tests to verify the new APIs. used test_pkg_validator.py and test_service_validator.py
> pip3 uninstall …

EOS-16423: S3 Mini-provisioner: Validations in post_install

---

py-utils/utils-pre-uninstall

While upgrading the cortx-py-utils package, as part of pre-uninstall
phase, all required packages were getting removed. This is not
expected in upgrade scenarios.
Made corrections in pre-uninstall script.

Handle upgrade of cortx-py-utils package

---

py-utils/src/utils/setup/msg_bus_test.py

Just after installing cortx-py-utils rpm, all other required
python packages are not installed. Hence need to move the "import"
functionality to methods in the class MessageBusTest.

Fix python package dependency issue

---

py-utils/src/utils/validator/v_pkg.py

commit 6889387c9ecca06b17a981ca4091622f8460f8d5
Date:   Mon Feb 8 05:24:42 2021 -0700
EOS-17370: cortx-utils: Stop using "--format=legacy" with pip3 in v_pkg.py due to incompatibility issues with newer pip3 versions
Description: Recent pre-merge mini-provisioner jobs require pip3 to be updated to 21.0.1 from 9.0.3. This breaks the existing use of pip3 in validator framework API while using "pip3 list – format=legacy". The "-- form
modified:   py-utils/src/utils/validator/v_pkg.py
Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>

EOS-17370: cortx-utils: Stop using "--format=legacy" with pip3 in v_pkg.py due to incompatibility issues with newer pip3 versions

---

py-utils/README.md
py-utils/requirements.txt
py-utils/setup.py

While installing cortx-py-utils, latest numpy package gets installed.
But the latest numpy (1.20 version) needs python 3.7. Hence explicitly
adding lower version (1.19.5) in requirements.txt. Required python
packages installation is handled for "pip".
"rpm" installation do not installs the dependent python packages.
Updated README mentioning the same.
-----
[View rendered py-utils/README.md](https://github.com/sachinpunadikar/cortx-utils/blob/fixpypackages/py-utils/README.md)

Fix python dependency for numpy

---

py-utils/README.md
py-utils/setup.py

A provision made, so that build command accepts version string, so that
rpm has the required version.
Signed-off-by: Sachin Punadikar <sachin.punadikar@seagate.com>
-----
[View rendered py-utils/README.md](https://github.com/sachinpunadikar/cortx-utils/blob/version_support/py-utils/README.md)

Support version string argument for cortx-py-utils

---

py-utils/src/utils/validator/v_pkg.py

commit 584b78e5610e6a01cd0852f295bac9881acc7035
Date:   Thu Feb 11 00:15:07 2021 -0700
EOS-17528:cortx-utils: In pkg validator dont check stderr if stdout is non-zero for pip3 pkgs
Description: In pkg validator dont check stderr if stdout is non-zero for pip3 pkgs
modified:   py-utils/src/utils/validator/v_pkg.py
test:
....
----------------------------------------------------------------------
Ran 4 tests in 5.176s
OK
Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>

EOS-17528:cortx-utils: In pkg validator dont check stderr if stdout is non-zero for pip3 pkgs

---

py-utils/README.md

Signed-off-by: Patrick Hession <patrick.hession@seagate.com>
Pip install wheel added as base CentOS does not come with this pre-installed.
-----
[View rendered py-utils/README.md](https://github.com/hessio/cortx-utils/blob/patch-1/py-utils/README.md)

Pip install wheel is required

---

py-utils/src/utils/validator/v_controller.py
py-utils/src/utils/validator/validate.py
py-utils/test/validator/test_controller_validator.py

[root@sm35-r5 utils]# python3 cortx/test/validator/test_controller_validator.py 10.0.0.2 manage 'testpass'
........
----------------------------------------------------------------------
Ran 8 tests in 18.612s
OK

EOS-15071: Add support for enclosure controller accessibility validator

---

py-utils/src/utils/conf_store/conf_cli.py

Error:
```
[root@ssc-vm-2516 ~]# conf json:///root/provisioner_cluster.json set "cluster>srvnode-1>machine_id=$MACHINEID"
error(22): invalid delim =
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/cortx/utils/conf_store/conf_cli.py", line 154, in main
out = args.func(args)
File "/usr/lib/python3.6/site-packages/cortx/utils/conf_store/conf_cli.py", line 43, in set
raise ConfError(errno.EINVAL, "invalid delim %s", kv_delim)
cortx.utils.conf_store.error.ConfError: error(22): invalid delim =
```
Signed-off-by: Bansidhar Soni <bansidhar.soni@seagate.com>

= delim added in valid list

---

jenkins/build.sh
py-utils/README.md

"cortx-py-utils" rpm depends on various python packages.
The %pre phase should check whether these python packages are
installed or not. If these packages do not exists, then throw
message asking to install them
-----
[View rendered py-utils/README.md](https://github.com/sachinpunadikar/cortx-utils/blob/pre_install_checks/py-utils/README.md)

Add pre-install checks for required python packages

---

py-utils/src/utils/validator/v_pkg.py

Unittest result:
```
[root 2021-03-09 ~]$ python3 utils_pgk_check_EOS-18332/cortx-utils/py-utils/src/utils/validator/validate.py Pkg pip3s zope.component
[root 2021-03-09 ~]$
[root 2021-03-09 ~]$
[root 2021-03-09 ~]$ python3 utils_pgk_check_EOS-18332/cortx-utils/py-utils/src/utils/validator/validate.py Pkg rpms cortx-py-utils
[root 2021-03-09 ~]$
```
```
[root 2021-03-10 ~]$
[root 2021-03-10 ~]$ python3 utils_pgk_check_EOS-18332/cortx-utils/py-utils/test/validator/test_pkg_validator.py -v
test_pip3_installed (__main__.TestRpmValidator)
Check if pip3 pkg installed. ... ok
test_remote_pip3_installed (__main__.TestRpmValidator)
Check if pip3 pkg installed. ... ok
test_remote_rpm_installed (__main__.TestRpmValidator)
Check if rpm pkg installed. ... ok
test_rpm_installed …
```

Validator - PkgV - Add version check on installed python 3rd party packages

---

py-utils/src/utils/ssh.py

Provision made to pass "allow_agent" parameter. Default value set to False.

Add allow_agent parameter for SSHChannel

---

py-utils/src/utils/log.py

This PR is to support CSM audit logs in JSON format. 
**Problem:** The timestamp field added in the log was giving issue while mapping CSM audit logs to ES structure.
**Resolution:** Removed timestamp for CSM audit logs.
Signed-off-by: Soniya Moholkar <soniya.moholkar@seagate.com>

Changes to support CSM audit log in JSON format

---

py-utils/src/utils/message_bus/message_broker_collection.py

confluent-kafka does not raise an unknown topic exception if it tries to send/receive for successive times.
A check is made on producer/consumer initialization and UNKNOWN_TOPIC_OR_PART error is thrown if topic does not exist.

EOS-20211: Raise exception for unknown topic for n retries

---

py-utils/src/utils/setup/openldap/openldap.py
py-utils/src/utils/setup/openldap/openldap_setup.py

This branch is cloned from parent branch `br/ms/EOS-19838-Openldap_provisioning` which has enabled the openldap provisioning and provides all necessary interfaces for phase-wise provisioning.
This branch implements the validations for post_install phase of openldap provisioning, as observed in the [HLD](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/268829518/OpenLDAP+in+CORTX+Environment).
Code implemented :
* openldap_setup binary ready for consumption/testing.
* Pre-requisites and keys validation in place for post_install.
* post_install deliverables.
Testing in progress, update so far :
* openldap_setup binary is available and accepts post_install argument.
* Test pre-requisite validation and keys validation for each post install phase.

EOS-19838 - [Openldap provisioning] Implement post_install with all validations in cortx-utils repository

---

py-utils/README.md

This existing README has this following line: `./jenkins/build.sh -v 2.0.0 -b 2` which will generate these following rpms:
```sh
cortx-py-utils-2.0.0-2_4e0eede.src.rpm
cortx-py-utils-2.0.0-2_4e0eede.noarch.rpm  
cortx-py-utils-2.0.0.tar.gz
```
However, when installing the RPM, the current script will look for version 1.0.0: `yum install -y cortx-py-utils-1.0.0-1.noarch.rpm`, which does not exist. Also, installing rpm should be executed by root. Therefore, the updated script should be: `sudo yum install -y cortx-py-utils-*.noarch.rpm`
Noted that this new input arg is utilizing `*` regex so that it can install any RPM regardless of the future version that will be generated.
-----
[View rendered py-utils/README.md](https://github.com/daniarherikurniawan/cortx-utils/blob/patch-1/py-utils/READM …

Update README.md: Correcting RPM version

---

py-utils/src/utils/cli_framework/command_factory.py

[EOS-22103](https://jts.seagate.com/browse/EOS-22103) - After the User model changed 'roles' field to 'role' the hack that turns the string parameter to list is no longer required.
-  Remove the hack that turns the string 'Roles' parameter to list.

EOS-22103: remove the roles hack from CommandFactory

---

py-utils/src/utils/data/db/consul_db/storage.py
py-utils/src/utils/data/db/db_provider.py
py-utils/src/utils/data/db/elasticsearch_db/storage.py

Signed-off-by: Soniya Moholkar <soniya.moholkar@seagate.com>
- Problem statement s3-rsys-index should not be generated through generic db framework
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/494600216/Rsyslog+and+Elasticsearch 

EOS-21195: Restrict schema generation if specified in config

---

py-utils/src/utils/data/access/queries.py
py-utils/src/utils/data/db/elasticsearch_db/storage.py

Signed-off-by: Soniya Moholkar <soniya.moholkar@seagate.com>
- Problem statement Sorting is not enabled on text fields in ES
-  For Bug describe the fix here. Using text field sub types, sorting is enabled
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/486114207/Elasticsearch-+Sorting+on+text+fields

EOS-21280: sorting enabled for text fields in ES

---

py-utils/src/setup/utils.py

- Factory reset(data+logs) command implementation failing as After cluster start Utils Kafka services were in failed state
- BUG
-  https://jts.seagate.com/browse/EOS-23280

EOS-23280: Factory reset(data+logs) command implementation failing as After cluster start Utils Kafka services were in failed state

---

py-utils/src/setup/utils.py

-  Method `_copy_cluster_map `  tries to load a file from a wrong conf index
-  added the argument for _copy_cluster_map method to take correct index name from parent method

EOS:23308 fix for Miniprovisioning fail

---

py-utils/src/utils/discovery/discovery.py
py-utils/src/utils/discovery/resource.py
py-utils/src/utils/discovery/resource_collection.py
py-utils/test/discovery/solution/lr2/health.json
py-utils/test/discovery/solution/lr2/server/server_resource_map.py
py-utils/test/discovery/test_discovery.py

- Decided to change compute type to server type for discovery in the SSPL Arch Roadmap meeting with @ujjwalpl 
-  Changed compute type to server type in discovery.

EOS-17458: Change compute type to server type in discovery

---

py-utils/setup.py
py-utils/src/support/support_bundle_cli.py
py-utils/test/support_bundle/test_support_bundle_cli.py

- Improve support_bundle_cli to provide all options like "cortxcli support_bundle" command
https://jts.seagate.com/browse/EOS-23314

EOS-23314: Improve support_bundle_cli to have options like "cortxcli support_bundle" command

---

py-utils/src/utils/data/db/elasticsearch_db/storage.py

Signed-off-by: Pranali04796 <pranali.ugale@seagate.com>
- Overview: EOS-22891:LIKE filter for Elasticsearch queries
- Currently the cortx-utils data framework does not support 'LIKE' operator for partial search. Elasticsearch supports full-text search using many ways. 
-  Used wildcard query for StringType data search to support partial text search
-  Coding conventions are followed and code is consistent [Y/N]: yes
-  Confirm All CODACY errors are resolved [Y/N]: yes

EOS-22891: LIKE operator implementation for Elasticsearch queries (For StringType)

---

py-utils/src/setup/setup.yaml
py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py

- Add  support for the pre-factory phase in mini-provisioning 
- added additional argument `--pre-factory` for cleanup phase in utils_setup
- if option `--pre-factory` passed, fetch and delete all the logs from `/var/log/cortx/utils`
-  Confirm All CODACY errors are resolved [Y/N]: N

EOS-22810: add support for pre-factory phase in mini-provisioning

---

py-utils/src/utils/data/db/openldap/storage.py

- 'Result' and 'Description' fields of LDAPError are not always set up, that raises additional exception during handling LDAP errors.
-  remove manual extraction of result and description from LDAPError

EOS-22632: Remove manual extraction of result and description from LDAPError

---

py-utils/src/utils/support_framework/bundle_generate.py
py-utils/test/support_bundle/test_support_bundle.py

- Component wise folders should be removed after support bundle generation
-  https://jts.seagate.com/browse/EOS-24017

EOS-24017: Component wise folders should be removed after support bundle generation

---

py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/support_framework/support_bundle.py
py-utils/test/support_bundle/test_support_bundle.py
py-utils/test/support_bundle/test_support_bundle_cli.py

- Handle non-existent component support bundle generation
- User should be get to know when he entered wrong component in SB generation
-  https://jts.seagate.com/browse/EOS-24154
- [x ] PR is self reviewed

EOS-24154: Handle non-existent component support bundle generation

---

py-utils/src/utils/setup/__init__.py

- Kafka related imports should be removed __init__.py file of setup package

EOS-24262: remove kafka setup classes imports from utils.setup init.py file

---

py-utils/src/utils/setup/openldap/base_configure_ldap.py
py-utils/src/utils/setup/openldap/configcmd.py
py-utils/src/utils/setup/openldap/openldap_prov_config.yaml
py-utils/src/utils/setup/openldap/setupReplication.py
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.1-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.3-node
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.3-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.1-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.3-node
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.3-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.1-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.3-node
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.3-node.sample
py-utils/src/utils/setup/openldap/test.py

Openldap provisioning failing with different Domain Component
seagate,com DC was hardcoded through ldif. Removed ldif and added data in py file to make it dynamic.

EOS24090 and EOS24092 and EOS23882-Openldap provisioning failing with different dc and different admin user and different pwd

---

py-utils/src/utils/setup/consul/consul_prvsnr.py
py-utils/src/utils/setup/consul/templates/consul.hcl.tmpl

- Use str replace to render template
Signed-off-by: Sandeep Anjara <sandeep.anjara@seagate.com>
- Third party dependencies should only be used if there is hard need. jinja2 used in consul mini provisioner can be removed easily and python native functions can be used to render template.

EOS-22576: Remove jina2 dependency from consul miniprovisioner

---

py-utils/src/utils/support_framework/support_bundle.py
py-utils/test/support_bundle/test_support_bundle_cli.py

- cortxcli support_bundle CLI should invoke utils code
-  https://jts.seagate.com/browse/EOS-24887

EOS-24887: cortxcli support_bundle CLI should invoke utils code

---

jenkins/build.sh
py-utils/src/setup/utils.py

- Python packages should be validated in post_install
-  The validation of correct python packages should be restored in both, utils rpm post_install as well as utils mini-prov post_install phase

EOS-24934: package validation restored in post_install phases

---

py-utils/src/utils/kv_store/kv_store_collection.py

- Consul was not able to connect to dc present on other hosts. It expects that host should be part of consul cluster
-  Added host and port information while creating the consul object
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316342315/Conf+Store

EOS-24922: Confstore: consul should be able to connect to consul cluster outside localhost

---

py-utils/src/utils/setup/openldap/base_configure_ldap.py
py-utils/src/utils/setup/openldap/cleanupcmd.py
py-utils/src/utils/setup/openldap/configcmd.py
py-utils/src/utils/setup/openldap/openldap_prov_config.yaml
py-utils/src/utils/setup/openldap/setupcmd.py
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.1-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.3-node
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.3-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.1-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.3-node
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.3-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.1-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.3-node
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.3-node.sample

Openldap install dir and data dir not configurable
Added 2 new keys to confstore and made both install and data path for openldap configurable

Making openldap install dir and data dir configurable

---

py-utils/src/setup/utils_setup.py

- in kubernetes environment, services hook is added in utils_setup to trigger services.
-  Added a new keyword argument, --services in all the stages of 
- [x ] PR is self reviewed
- [x ] Jira is updated
- [ x] Check if the description is clear and explained. 
- [ x] Check Acceptance Criterion is defined.

EOS-24935: add services hook in utils_Setup

---

jenkins/build.sh

- add run time yum packages dependency to cortx-py-utils rpm
-  added python36 and python36-dbus as dependency in rpm build stage of cortx-py-utils

EOS-24944: Dependent yum packages for utils should be installed as dependency

---

py-utils/src/utils/common/common.py

- In the current k8 utils log files are created inside "/shared/log/**cortx/cortx**/utils/message_bus". 
- Fixed by updating and binding the log path from utils.

EOS-24442: Updated K8 log path for utils

---

py-utils/src/setup/utils.py
py-utils/src/utils/common/common.py

- make path of cortx.conf file path configurable
- As of now, cortx.conf file is in /etc/cortx path. This path needs to be made configurable, we need to read the path present in cluster.conf, under local key.
-  https://jts.seagate.com/browse/EOS-25118

EOS-25118: Make path of cortx.conf file path configurable

---

py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py
py-utils/src/utils/common/common.py

- Make path of cortx.conf file path configurable for utils
-  https://jts.seagate.com/browse/EOS-25118

EOS-25118: Make path of cortx.conf file path configurable for utils

---

py-utils/src/setup/utils.py
py-utils/src/utils/message_bus/message_bus.py

- make message_bus.conf file configurable
-  take base path from CortxConf.get_storage_path('local') instead of using /etc/cortx

EOS-25113: make path of message_bus.conf file path configurable

---

py-utils/src/setup/utils.py
py-utils/src/utils/iem_framework/event_message.py

- https://jts.seagate.com/browse/EOS-25112
-  Make iem.conf path configurable from cortx>common>storage>local

EOS-25112: Make iem.conf path configurable

---

py-utils/src/setup/utils.py

Signed-off-by: Rahul Tripathi rahul.tripathi@seagate.com
- utils_Setuup init phase was raising exception in case IEM topic is already present in kafka
-  The exception is suppressed for topic already exists.

IEM topic creation in init phase fixed

---

py-utils/src/setup/utils.py

- Fix for getting utils path in utils_setup test phase

Fix for getting utils path in utils_setup test phase

---

py-utils/src/utils/setup/openldap/base_configure_ldap.py

userpassword entry was getting overwritten in base config as a result other component's config were failing
Added the userpassword instead of replacing it

EOS25102- openldap config causing access rights issues

---

py-utils/src/utils/common/common.py

- Allow CortxConf init to reload.

EOS-25253: Enhance CortxConf class to take cluster.conf file path as input

---

py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py

- Uitls mini provisioning code changes for accepting cluster.conf as input variable
- Lazy load messagebus classes

EOS-25329: Utils Setup - mini provisioning cluster.conf as input variable

---

py-utils/src/support/support_bundle_cli.py
py-utils/src/utils/support_framework/support_bundle.py

- Enhance Support Bundle interfaces to take cluster.conf file path as input
-  https://jts.seagate.com/browse/EOS-25257

EOS-25257: Enhance Support Bundle interfaces to take cluster.conf file path as input

---

py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py

- Pass config_file path to MessageBusAdmin in untils_setup
- added config_path parameter to init and reset method to accept template file and pass to MessageBusAdmin class instantiation

patch to accept cluster.conf path from end user in utis_setup

---

py-utils/src/support/cortx_support_bundle.py
py-utils/src/utils/common/common.py
py-utils/src/utils/support_framework/bundle.py
py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/support_framework/const.py
py-utils/src/utils/support_framework/support_bundle.py
py-utils/src/utils/support_framework/support_bundle.yaml

- Generate support Bundle inside K8s env.
-Finalized Design for SB generation:
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/749076684/Node+level+Support+Bundle+Collection
- [Y] Confirm Testing was performed with installed RPM [Y/N]:  
- [] All the tests performed should be mentioned before Resolving a JIRA. 
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/749076684/Node+level+Support+Bundle+Collection

EOS-25148: Generate support Bundle inside K8s env.

---

py-utils/src/utils/setup/kafka/kafka.py
py-utils/src/utils/setup/kafka/setup.yaml

- Cleanup phase added blank lines where the config was deleted
-  The default value of end in print is '\n', hence added end='' to print which deletes the line instead of replacing it with a blank line

EOS-25035 : Fix blank lines in kafka mini provisioning cleanup phase

---

py-utils/src/utils/kv_store/kv_store_collection.py
py-utils/test/kv_store/test_kv_store.py

-Enable dict kv store. added test cases
-  Added test cases for dict kv store. 
- input format: 'dict:{"k1":v1}' or it can be an empty dict: 'dict:{}',
- input dictionary should be a jsonified string.
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316342315/Conf+Store#Using-Dict-KV-store

EOS-22305: KvStore - DictKvStore implementation

---

py-utils/src/setup/utils.py
py-utils/src/utils/iem_framework/event_message.py
py-utils/src/utils/message_bus/message_bus.py

- We need to move away from messagebus.conf and iem.conf and merge them both into a single file, utils.conf.

EOS-25744: Merged message bus and iem conf into single utils conf file utils.conf

---

py-utils/test/conf_store/test_conf_store.py
py-utils/test/kv_store/test_kv_store.py

- Adding Conf store tests with DictKVstore as backend and KVstore dict tests.
- https://jts.seagate.com/browse/EOS-25753
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316342315/Conf+Store#Using-Dict-KV-store

Adding Conf store tests with DictKVstore as backend and KVstore dict tests.

---

py-utils/src/utils/message_bus/message_broker_collection.py
py-utils/src/utils/message_bus/message_bus.py
py-utils/src/utils/message_bus/message_bus_client.py
py-utils/test/message_bus/test_message_bus.py

- A message type should have an expiration time, such that if a message was not read within the expiration time, it should get removed from message bus.
- mb_admin.set_message_type_expire('message_type', time_to_expire_in_milli_sec)

EOS-26043: Implement Expiration time filter for messages for a particular topic

---

py-utils/src/setup/utils.py
py-utils/src/utils/common/common.py

- BUG
- /opt/seagate/cortx/motr/bin/motr_setup post_install fails after glusterfs removal
-  https://jts.seagate.com/browse/EOS-26737

EOS-26737: BUG - /opt/seagate/cortx/motr/bin/motr_setup post_install fails after glusterfs removal

---

py-utils/src/setup/setup.yaml
py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py

- Utils mini-provisioner should support "upgrade" phase
-  As utils has no direct dependency on configuration files, this phase will be simply pass-through, no action will be required.

EOS-26723: Support upgrade phase in utils mini-provisioner

---

py-utils/setup.py
py-utils/src/utils/cortx/__init__.py
py-utils/src/utils/cortx/const.py

- Added cortx constants for service names and component names
-  Added a new subpackage.module -> cortx.utils.cortx.const.py
- To import const class -> `from cortx.utils.cortx import Const` OR `from cortx.utils.cortx.const import Const`

EOS-26878: add cortx.const in utils for defining constants of service name and components

---

py-utils/setup.py
py-utils/src/utils/audit_log/__init__.py
py-utils/src/utils/audit_log/audit_log_server.py
py-utils/src/utils/audit_log/error.py
py-utils/src/utils/utils_server/utils_server.py
py-utils/test/audit_log/test_audit_log_server.py

- S3 Audit Log: Expose an API to push audit logs
-  https://jts.seagate.com/browse/EOS-26021

EOS-26021: S3 Audit Log: Expose an API to push audit logs

---

py-utils/src/setup/utils.py
py-utils/src/utils/message_bus/message_broker.py
py-utils/src/utils/message_bus/message_broker_collection.py
py-utils/src/utils/message_bus/message_bus.py
py-utils/src/utils/message_bus/message_bus_client.py
py-utils/src/utils/message_bus/message_bus_server.py
py-utils/test/message_bus/test_message_bus.py
py-utils/test/message_bus/test_message_bus_server.py

- MessageBus code is a library code. This code is currently referring to config file (utils.conf & cluster.conf) for its execution. This  is incorrect, and the code should not rely on any config files.
-  Added a new method "MessageBus.init()" which takes care of information read from conf files.
- [] Jira is updated

MessageBus library code should not refer any conf file

---

py-utils/src/utils/message_bus/message_bus.py

- MessageBus throws error if logger is not initialised by the component who uses it
-  https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/349307984/CORTX+Message+Bus

Make use of components logger

---

py-utils/src/utils/kv_store/kv_store_collection.py

`
$# Error reproduced
$#Load yaml and consul config.
>>> from cortx.utils.conf_store import Conf 
>>> Conf.load('yaml_conf', 'yaml:///root/auto-gen-cfgmap/config.yaml') 
>>> Conf.load('consul_conf', 'consul://ssc-vm-g3-rhev4-2114.colo.seagate.com:8500')
$#Get, set, delete opration on consul
>>> Conf.set('consul_conf', 'test>key', 'val') 
>>> Conf.get('consul_conf', 'test>key') 
>>> 'val' 
>>> Conf.delete('consul_conf', 'test>key') True 
>>> Conf.get('consul_conf', 'test>key') 
$#copy from yaml config to consul config
>>> Conf.copy('yaml_conf', 'consul_conf') 
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.6/site-packages/cortx/utils/conf_store/conf_store.py", line 286, in copy
Conf._conf.copy(src_index, dst_index, key_list, recurse)
File …

EOS-26982: ConfStore Consul copy-set api changes

---

py-utils/src/utils/message_bus/message_broker_collection.py
py-utils/src/utils/message_bus/message_bus.py
py-utils/src/utils/message_bus/message_bus_client.py
py-utils/test/message_bus/test_message_bus.py

- Analyze and work on existing expiration time argument per topic basis,
From the consumer side, work on a message filter that should skip expired messages for a given topic.
Existing:
Users can define an expiration time for messages under individual topics dynamically by the below statement.
Example:
admin.set_message_type_expire(message_type, time_out_period)
Current timeout logic will clean the offset after expire time of the entire message logs. In this way, the new consumer joins after the log cleanup won't receive the old message.
Need to be done:
The next step needs to sketch a logic to ensure that the existing consumer who try to read messages that already passed their expiration period must not receive any old message logs.
-  For Feature, Post …

EOS-26730: Customization of message type

---

py-utils/test/message_bus/test_message_bus.py

- Messagebus testcase changes to address set_message_type_expire() parameters api changes
- set_message_type_expire accept message_type, expire_time_ms and data_limit_bytes as parameters
- Since existing test code doesn't handle following params: expire_time_ms and data_limit_bytes
-  Updated position of test cases to ensure other test case values not affected.
- Fixed test cases of expire changes
- handled and passed message_type, expire_time_ms and data_limit_bytes as arguments to set_message_type_expire() method

EOS-26730: Test case update for customization of message type API

---

py-utils/test/message_bus/test_kvpayload_message.py
py-utils/test/message_bus/test_message_bus.py

- Update message_bus tests to take cluster.conf path as input and get kafka endpoints from conf.
-  https://jts.seagate.com/browse/EOS-27045 
-  Confirm All CODACY errors are resolved [Y/N]: N

Updated message_bus tests to take cluster.conf path as input and get kafka endpoints from conf.

---

py-utils/src/utils/kv_store/kv_store_collection.py
py-utils/test/kv_store/test_consul_kv_store.py

- When a blank string as a value is loaded in yaml/json ConfStore, and then copied to consul backend, all the empty strings are converted to null. which is giving error and this needs to be handled.
-  null/None value is explicitly handled and instead of None, empty string is returned. 

EOS-27054: handle null value in consul kv

---

py-utils/src/setup/utils.py
py-utils/src/utils/audit_log/audit_log_server.py
py-utils/src/utils/utils_server/utils_server.py
py-utils/test/audit_log/test_audit_log_server.py

- REST API to accept webhook information in utils rest server
-  https://jts.seagate.com/browse/EOS-26066

EOS-26066: REST API to accept webhook information in utils rest server

---

py-utils/src/utils/iem_framework/event_message.py
py-utils/test/iem_framework/test_iem.py

- DoD:
- Implement IEM prep() and init() method
- Update the code not to refer to any config file
- Update test cases to make use of the prep(), init () method & initialize log files
-  Implemented new iem.prep() method that will get cluster_id and server endpoints as input.
- iem.prep() should be invoked before iem.init().
- iem.prep() will internally initialize message bus init method.

EOS-25893: Implement init method for Event_message

---

py-utils/src/utils/message_bus/message_broker_collection.py
py-utils/src/utils/message_bus/message_bus.py
py-utils/src/utils/message_bus/message_bus_client.py
py-utils/test/message_bus/test_message_bus.py

- Message bus code should not use kafka binaries for get_unread_count.
-  Removed code that uses kafka binaries
-----
[View rendered py-utils/src/test_framework/README.md](https://github.com/selvakumaar5496/cortx-utils/blob/mb_unread/py-utils/src/test_framework/README.md)

EOS-26912: Removal of get_unread_count()

---

py-utils/src/utils/schema/release.py

EOS-27087:Version compatibility check.

---

py-utils/src/setup/utils.py
py-utils/src/utils/message_bus/message_bus.py

- MesageBus expire api not working due to old arguments introduced during merge conflicts
- MessageBus backend value is hardcoded
-  Fixed but updating the message bus script with proper kwargs instead of old expire time arguments
-  Read message_bus_backend from confstore

Fix set_message_type_expire params

---

py-utils/src/utils/common/common.py
py-utils/src/utils/conf_store/__init__.py
py-utils/src/utils/conf_store/conf_store.py
py-utils/src/utils/support_framework/support_bundle.py

- Refactoring code for Confstore 
moved ConfigStore class from https://github.com/Seagate/cortx-prvsnr/blob/main/src/provisioner/config_store.py to https://github.com/Seagate/cortx-utils/blob/main/py-utils/src/utils/conf_store/conf_store.py

EOS-27348: Refactor - move Configstore -> MappedConf to cortx-utils

---

py-utils/src/utils/conf_store/conf_store.py

- Patch to accept default_val in MappedConf.get
-  Added default_val arg in MappedConf
- 

EOS-27348: add default val_args to MappedConf.get

---

py-utils/src/utils/conf_store/conf_store.py

- After every change in MappedConf class we do save the changes back to the conf backend. Set API works as expected but delete API does not save the changes after a delete operation.
-  Added conf save API after every MappedConf delete API.

MappedConf - Delete: Added save option after each MappedConf delete operations

---

py-utils/src/support/cortx_support_bundle.py
py-utils/src/support/utils_support_bundle.py
py-utils/src/utils/const.py
py-utils/src/utils/discovery/request_handler.py
py-utils/src/utils/setup/kafka/kafka_setup.py
py-utils/src/utils/setup/openldap/setupcmd.py
py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/support_framework/support_bundle.py
py-utils/src/utils/utils_server/utils_server.py
py-utils/test/discovery/test_discovery.py

- Replace use of CortxConf class with MappedConf 

EOS-27348: replace use of CortxConf class to MappedConf

---

py-utils/src/support/cortx_support_bundle.py

- changed cortx support bundle to fetch log directory from `cortx>common>storage>log`  key instead of `log_dir`
JIRA: https://jts.seagate.com/browse/EOS-28411

EOS-28411: Support bundle not getting generated

---

jenkins/build.sh

- python36-bdus is not availabel in rocky linux ,instead it utilises python3-dbus

EOS-27916: added dependency check for different os in build.sh

---

py-utils/src/utils/conf_store/conf_cache.py
py-utils/src/utils/conf_store/conf_cli.py
py-utils/src/utils/conf_store/conf_store.py
py-utils/src/utils/kv_store/kv_payload.py
py-utils/src/utils/kv_store/kv_store.py
py-utils/test/conf_store/test_conf_store.py

Signed-off-by: Ujjwal Lanjewar <ujjwal.lanjewar@seagate.com>
- "Addsnum keys for the list items" 
"Example Command:"
"# conf  yaml:///tmp/test.conf addnumkeys 
The count would be helpful for iterating through the number of services and components in gconf 

EOS-27645: Added provision to add num keys to conf

---

py-utils/src/utils/rgwadmin/client.py

- RGWAdminClient fails to sign create_key request properly.
-  Remove query parameters from the path before signing the request
- E.g. from the path like '/admin/user?key' remove '?key' 

EOS-28599: remove query parameters from the path before signing the request

---

py-utils/src/utils/conf_store/conf_cache.py
py-utils/src/utils/conf_store/conf_cli.py
py-utils/src/utils/conf_store/conf_store.py
py-utils/src/utils/kv_store/kv_payload.py
py-utils/src/utils/kv_store/kv_store.py
py-utils/test/conf_store/test_conf_store.py

- Missing num_data & num_metadata keys in cluster.conf
cvg:
- devices:
data:
- /dev/sdd
- /dev/sde
metadata:
- /dev/sdc
name: cvg-01
type: ios
Expected num keys for data & metadata (wherever applicable)
cvg:
- devices:
data:
num_data: 2
- /dev/sdd
- /dev/sde
metadata:
num_metadata: 1
- /dev/sdc
name: cvg-01
type: ios
-  https://jts.seagate.com/browse/CORTX-29052

CORTX-29052: fix: num_keys are missing for list/array type values in cluster.conf

---

py-utils/src/utils/utils_server/utils_server.py

- Message Server runs on 8080 by default since port value is returned as None
-  ConfStore should set value as 28300(assigned for message_server) if Conf.get returns None

CORTX-29181: Update message_server port if value is None

---

py-utils/src/utils/conf_store/conf_cache.py
py-utils/src/utils/conf_store/conf_store.py
py-utils/src/utils/kv_store/kv_payload.py
py-utils/test/conf_store/test_conf_store.py

- Disable deletion of non-leaf key until force parameter is passed
-  recurrsive deletion of keys are restricted until `force=True` is passed to `Conf.delete(index, key, force)`

CORTX-29025 : Disable deletion of non leaf keys

---

py-utils/src/utils/kv_store/kv_store_collection.py

- Ini test failed in the delete operation
-  ini doesn't allows multilevel keys hence delete operation is implemented separately, added a force key which is never used as a key can only be leaf node in ini format and having multi-level key will any way throw error as it is not a valid key for ini
-  Consul supports recurrsive deletion of keys if a key is not leaf key `consul.kv.delete(key, recurse=None, cas=None, token=None, dc=None)`, so passed force to recurse enables force deletion of non leaf keys in consul

CORTX-29256: Patch for force delete in ini and consul 

---

py-utils/src/utils/conf_store/conf_cli.py
py-utils/test/conf_store/test_conf_cli.py

- Add force option to delete non-leaf key and its child key-value pairs
- JIRA: https://jts.seagate.com/browse/CORTX-29225

CORTX-29225: Add force option to conf_cli

---

py-utils/src/utils/conf_store/conf_cli.py
py-utils/test/conf_store/test_conf_cli.py

fixed cli diff code
- conf_store CLI test 'test_conf_cli_by_get_diff' is failing.
-  Fixed ConfStore CLI diff -> get call implementation with arg.format as none
-  Fixed test case by making deepcopy of files configs

CORTX-29185: Fix ConfStore-CLI get_diff test case

---

py-utils/src/test_framework/const.py
py-utils/test/conf_store/config.yaml
py-utils/test/conf_store/test_conf_store_conf.py
py-utils/test/kv_store/config.yaml
py-utils/test/kv_store/test_consul_kv_store.py
py-utils/test/kv_store/test_kv_store.py
py-utils/test/setup.py

Signed-off-by: VidyaKabber <vidya.kabber@seagate.com>
- Consul backend test cases is running on localhost in K8's environment
- Jira Ticket : [CORTX-29208](https://jts.seagate.com/browse/CORTX-29208)
- 
-  Coding conventions are followed and code is consistent [Y]: 
-  Confirm All CODACY errors are resolved [Y]: 

CORTX-29208 : Consul backend test cases reaching out to consul endpoints mentioned in cluster.conf

---

py-utils/src/utils/kv_store/kv_store_collection.py
py-utils/test/conf_store/test_conf_store.py

- redundant code in classes JsonMessageKvStore & DictKvStore
- Derived JsonMessageKvStore from DictKvStore  to avoid redundancy of code
-  derived JsonMessageStore from DictKvStore

CORTX-29022: Derive JsonMessageKvStore from DictKvStore 

---

py-utils/src/utils/kv_store/kv_payload.py
py-utils/test/conf_store/test_conf_store.py
py-utils/test/kv_store/test_kv_store.py

JIRA: https://jts.seagate.com/browse/CORTX-29612
- None is being used as blank value which is not a recognized blank value outside python environment(json, ini, yaml) 
-  Use empty string `' '` as blank values instead of `None`

CORTX-29612: Use empty string as blank values instead of none

---

py-utils/src/setup/utils.py

- Rpm installation already checks for required pip packages
- Removed pip packages validation in the post_install phase

CORTX-29339: remove redundant pip packages check from post_install phase

---

py-utils/src/utils/kv_store/kv_payload.py
py-utils/test/conf_store/test_conf_store.py

- After deletetion of keys from conf, Conf.get_keys() still returns the deleted keys.
-  Fixed the get_keys logic

CORTX-29642: fixed get_keys. Keys were not getting del from get_keys

---

py-utils/src/utils/conf_store/conf_cache.py
py-utils/src/utils/conf_store/conf_cli.py
py-utils/src/utils/conf_store/conf_store.py
py-utils/src/utils/kv_store/kv_payload.py
py-utils/src/utils/kv_store/kv_store_collection.py
py-utils/test/conf_store/test_conf_store.py
py-utils/test/conf_store/test_conf_store_conf.py

- non str values should not be allowed to set in conf/kv store. #Supporting byte strings
-  checking for type of input value provided by user. #Supporting byte strings

CORTX-29608: Disable set api for non string type values in confstore

---

py-utils/src/utils/log.py

JIRA: https://jts.seagate.com/browse/CORTX-30383
- Redirect error and warning logs to std out
-  check for `console_warn` and `console_error` and set sessionHandler log level respectively
-  Coding conventions are followed and code is consistent (Y/N): 
-  Confirm All CODACY errors are resolved (Y/N): 

CORTX-30383: redirect log to stdout in docker environment

---

py-utils/src/utils/common/__init__.py
py-utils/src/utils/common/common.py
py-utils/src/utils/kv_store/kv_store_collection.py

- Since confstore branch is discarded, raised a separate PR for retry mechanism in consul.
-  These changes are pre approved changes from confstore branch, now raised the same changes against main branch.
relevant PRs: https://github.com/Seagate/cortx-utils/pull/776, https://github.com/Seagate/cortx-utils/pull/753
- Confirm Test Cases cover Happy Path, …

CORTX-23443:  adding retry decorator in consul confstore in main

---

py-utils/test/conf_store/test_conf_store_mapped_conf.py

Signed-off-by: Kailash Yadav <kailash.yadav@seagate.com>
- Fix the problem where any operation like add_num_keys, or set, or delete is in memory operation and should not reflected until explicit save
-  adding unit test cases to cover the problem statement scenario
- Confirm Test Cases cover Happy Path, Non-Happy Path and …

CORTX-30863: added unittest for mapped conf api add_num_keys

---

py-utils/src/utils/event_framework/event.py
py-utils/test/event_framework/test_health_event.py

Signed-off-by: gauri-bhosale <gauri.bhosale@seagate.com>
-  https://jts.seagate.com/browse/CORTX-29731
- event_id should contain timestamp but not should contain floating value 
- so need to convert into integer before string conversion
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]: Y
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]: Y
- Confirm that Test Cases are added for new features added [Y/N]:  Y 
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  Y
Testing result :
sh-4.4# pytest test_health_event.py
======================================= test …

CORTX-29731: system_health even-id getting floating value

---

py-utils/test/iem_framework/test_iem.py
py-utils/test/message_bus/test_message_bus.py

JIRA: https://jts.seagate.com/browse/CORTX-31268
- kakfa topic message expiry relies not just on the topic's  expire_time_ms parameter but also on  log.retention.check.interval.ms & segment.ms from server.properties. hence removed test_017_message_type_read_after_expiry as its not a fair assumption to set only expire time anch check after that interval
- for iem test case, made sure it considers only the intended message to verify the count
-  increese sleep time to consider 300000ms of delay in message expire check
- Confirm that new …

CORTX-31268: fix test test_bulk_alert_send and remove test_017_message_type_read_after_expiry 

---

py-utils/src/utils/conf_store/conf_cli.py
py-utils/src/utils/conf_store/conf_store.py
py-utils/test/conf_store/test_conf_cli.py
py-utils/test/conf_store/test_conf_store.py

Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>
Add Conf. compare utility in confstore for comparing two kVstores and return new/deleted/updated keys .
Also add Conf compare CLI support for the same.
Using Confstore Compare, If Two Indexes are passed, this function should return the difference between two indexes in a way that it would return three lists: new keys, deleted keys, and updated keys.
Example conf.compare:
>>> from cortx.utils.conf_store import Conf, MappedConf
>>> Conf.load('index1',"yaml:///etc/cortx/cluster.conf")
>>> Conf.load('index2',"yaml:///tmp/tmp.conf")
>>>
>>> new_keys, updated_keys, deleted_keys = Conf.compare('index1','index2')
>>> print(new_keys)
['node>8efd697708a8f7e428d3fd520c180795>provisioning>status', …

[WIP] CORTX-31132: added conf.compare in confstore for comparing two indexes

---

py-utils/src/utils/conf_store/conf_cache.py
py-utils/src/utils/conf_store/conf_cli.py
py-utils/src/utils/conf_store/conf_store.py
py-utils/src/utils/kv_store/kv_payload.py
py-utils/src/utils/kv_store/kv_store_collection.py
py-utils/test/conf_store/test_conf_cli.py
py-utils/test/conf_store/test_conf_store.py
py-utils/test/conf_store/test_conf_store_mapped_conf.py
py-utils/test/kv_store/test_consul_kv_store.py
py-utils/test/kv_store/test_kv_store.py

Raised this PR for PR:https://github.com/Seagate/cortx-utils/pull/814
Above PR had DCO failures with good number of commits hence had raised this PR with all the changes present in PR: #814
**This PR includes changes from following PRs:**
https://github.com/Seagate/cortx-utils/pull/749
https://github.com/Seagate/cortx-utils/pull/746
https://github.com/Seagate/cortx-utils/pull/755
https://github.com/Seagate/cortx-utils/pull/756
https://github.com/Seagate/cortx-utils/pull/763
https://github.com/Seagate/cortx-utils/pull/779
https://github.com/Seagate/cortx-utils/pull/780
Relevant Stories:
[CORTX-29612](https://jts.seagate.com/browse/CORTX-29612): ConfStore: instead of None, use empty string as a null value …

CORTX-29612: CORTX-29642: Confstore: alternate PR for PR #814 (DCO check issue)

---

py-utils/src/utils/s3/client.py

- [CORTX-31950](https://jts.seagate.com/browse/CORTX-31950): CSM-S3 communication should be on https.
-  Per Pranay's request make S3 client capable of handling URL provided as is instead of constructing from host, port and tls_enabled arguments.
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  
- [] All the tests …

CORTX-31950: add url to kwargs for S3Client constructor

---

c-utils/scripts/build.sh
py-utils/test/ssh_connection/test_ssh_connection.py

Signed-off-by: rohit-k-dwivedi <rohit.k.dwivedi@seagate.com>
- use of sudo is discouraged
-  removed use of sudo from codebase

CORTX-32122: remove sudo usage

---

py-utils/src/utils/kv_store/kv_store_collection.py
py-utils/test/kv_store/test_consul_kv_store.py

- Conf.Search is not working with search_val for consul backend
-  modified code to work without search val as well
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]: Y
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]: Y
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: Y
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  K8s dployment will happen for this PR

CORTX-33600: Conf.search not working without value

---

py-utils/src/utils/query_deployment/query_deployment.py

Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>
- add deployment_time field in the topology/ output of query_deployment which will be used by CSM.
extracting 'time' field from 'provisioning' under each node as part of node_info for each node in query deployment output
- Confirm Testing was performed with installed RPM/K8s …

CORTX-33672: added deployment time in Query deployemnt

---

py-utils/src/utils/support_framework/support_bundle.py

Signed-off-by: Sachitanand Shelake <sachitanand.shelake@seagate.com>
- With Gconfstore migration to consul, there is structural change on the way we fetch any component list values. Eariler sprint we have fixed for actual utils code but somehow we missed this change for support bundle script in utils.
-  For fetching component names list, first we need to fetch num_components key and then iterate over this number for fetching actual component name key.
- similar changes required for fetching services names.
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]: N
- Confirm that new test cases are added to regression and sanity plan files and …

CORTX-33790:utils:Fix for fetching component & service names in support bundle

---

.github/auto_assign.yml

Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
- Added Codeowner for Utils

CORTX-32168: Added Codeowner for Utils

---

py-utils/src/utils/conf_store/conf_store.py
py-utils/test/conf_store/test_conf_lock_unlock.py

Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>
- Unit test cases for lock and unlock interface
This PR covers following test cases for lock and unlock suggested by Ujjwal:
1. test “test_lock” interface
2. test “lock” interface
3. test “lock” repeat
4. lock at one thread and test “lock” from a different thread
5. lock at one thread and test “unlock” from a different thread
6. test “unlock” interface
7. test “unlock” repeat
8. unlock from one thread and test “lock” from another
9. lock from one thread and test “unlock with force=true” from another thread
10. force unlock from one thread and test repeat “unlock” from another thread after
11. test “lock” interface with duration n seconds
test case results:
`[root@ssc-vm-g4-rhev4-2113 conf_store]# python3 …

CORTX-33672: added unit test cases for lock and unlock interface

---

.github/auto_assign.yml
py-utils/src/utils/query_deployment/query_deployment.py

Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>
- The data in clusters field of output topology of query deployment is in string format need to change it into dictionary.
-  convert json.dumps value to dict by doing json.loads
- Confirm …

CORTX-33856: str to dict in topology

---

py-utils/src/utils/support_framework/log_filters.py

Problem: 
Support bundle creation is failing in limit_time filter for rotated log (.gz) files.
Solution:
For now to unblock the sanity skip rotated files while applying limit_time filter during log collection.
- Confirm that Test Cases are added for new features added [Y/N]: …

CORTX-34050: support bundle: rgw log directory not present in server pod logs.

---

py-utils/src/utils/support_framework/log_filters.py

- Handle processing for .gz files while applying the limit_time filter.
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  Y

CORTX-34050: Apply limit_time filter on .gz files.

---

py-utils/src/utils/support_framework/log_filters.py

- If the container contains multiple compressed log '.gz' files in that case RGW support bundle collection is failing with `-9` error code, which means the process is killed via SIGKILL. It's probably due to the machine/node running out of memory or the script needing too much memory and the OS kernel was triggering the OOM killer.
- It is failing while reading the larger size `.gz` file contents using gzip.readline().
-  Instead of reading the `.gz` file contents, include these files in the support bundle if file creation time is in between the given time duration.
- Are test cases updated along with code changes …

CORTX-34143: k8 support bundle script fails to collect cortx-rgw files.
