py-utils/src/utils/ha/dm/decision_monitor.py

Reverts Seagate/cortx-utils#18
Pull request to revert patch
as it is filling log we can avoid it

Revert "decision_log: Add more log to get resource action"

---

py-utils/src/utils/validator/commands.py
py-utils/src/utils/validator/v_consul.py
py-utils/src/utils/validator/v_network.py
py-utils/src/utils/validator/validate.py
py-utils/test/validator/test_consul_validator.py
py-utils/test/validator/test_network_validator.py

**Problem Statement**
Generic Validator framework
**Problem Description**
No segregation for type of validation in validator
**Solution Overview**
Added v_type parameter to validate method
Signed-off-by: Shri Bhargav Metta <shri.metta@seagate.com>

Added v_type parameter to validate method

---

py-utils/src/utils/validator/commands.py
py-utils/src/utils/validator/service.py
py-utils/src/utils/validator/v_elasticsearch.py
py-utils/src/utils/validator/validate.py
py-utils/test/validator/test_elasticsearch_validator.py

**Problem Statement**
Validator for elasticsearch service
**Solution Overview**
Implemented validator for elasticsearch service
Signed-off-by: Shri Bhargav Metta <shri.metta@seagate.com>

Implemented elasticsearch validator

---

py-utils/src/utils/validator/v_network.py
py-utils/test/validator/test_network_validator.py

Signed-off-by: mazinamdar <mazhar.inamdar@seagate.com>
1. network ip_connectivity <ip1> <ip2> <ip3>
2. network host_connectivity <host1> <host2>

[Network] ip and host connectivity checks

---

statsd-utils/statsd-elasticsearch-backend-0.4.2/lib/elasticsearch.js

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>
<pre>
<code>
Elasticsearch statsd connection fails
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
req = http.request(reqOpts, function (res) { });
Here, request error not handled causing Elasticsearch to restart.
</code>
</pre>
<pre>
<code>
req = http.request(reqOpts, function (res) { });
Handled error for connection request
</code>
</pre>
<pre>
<code>
Tested on vm with es - statsd connecton.
</code>
</pre>

Statsd Elasticsearch connection error handle

---

c-utils/src/include/internal/management-internal.h
c-utils/src/include/management.h
c-utils/src/management/CMakeLists.txt
c-utils/src/management/error_response.c
c-utils/src/management/request-handler.c

_[EOS-13967](https://jts.seagate.com/browse/EOS-13967):_
_REST API error response framework_
_Define an error response structure. 
like defined here https://github.com/Seagate/cortx-fs/blob/main/doc/RESTAPI_Guidelines.md
Use that JSON object to send an error response to the client_
1. error response structure which holds the string: description, int: rc, int: HTTP error code
2. Map structure for mapping rc or HTTP code to error msg
3. the function which prepares or initializes this error response structure from rc
4. the function which returns a proper JSON object out of this error response object 
_No new test cases added_
<details>
<summary>Click here to see the test execution output</summary>
```
723986@ssc-vm-c-0219.colo.seagate.com:/home/723986/abc/cortx-posix (main)
$ sudo …
```

EOS-13967: Implemented error response framework and integrated with request structure

---

py-utils/requirements.txt
py-utils/src/utils/comm.py
py-utils/src/utils/ssh.py
py-utils/test/test_ssh_connection.py

As requested in PR(#66 ), I separated framework changes from validators PR(#66 ) work.
@ujjwalpl @cdeshmukh 
Unit test result:
> [root@smc39-m09 utils]# python3 -m unittest -v cortx/test/test_ssh_connection.py
> **test_command_execution_ok** (cortx.test.test_ssh_connection.TestSSHSession)
> Check if command is executed successfully ... useradd: cannot create directory /home/utiltester
> ok
> **test_connection_ok** (cortx.test.test_ssh_connection.TestSSHSession)
> Check if ssh connection is alive ... useradd: cannot create directory /home/utiltester
> ok
> **test_reconnect_ok** (cortx.test.test_ssh_connection.TestSSHSession)
> Check ssh re-connect after disconnection caller ... useradd: cannot create directory /home/utiltester
> ok
> 
> …

EOS-15069: Add SSH Session into comm.py

---

py-utils/src/utils/data/db/consul_db/storage.py
py-utils/src/utils/data/db/db_provider.py
py-utils/src/utils/data/db/elasticsearch_db/storage.py
py-utils/src/utils/data/db/examples/consul_storage.py
py-utils/src/utils/data/db/examples/elasticsearch_storage.py
py-utils/src/utils/schema/database.py

Fixes #Reverts Seagate/cortx-utils#99
Implement multiple hosts configuration for Elasticsearch
<pre>
Story Ref (if any):
</pre>
EOS-15055
<pre>
No (Pending)
</pre>
<pre>
Changes causing problem as all condition not properly handled
also all component using this change are getting failed
</pre>
<pre>
Revert change
</pre>
<pre>
No
</pre>

Revert "EOS-15055 Multiple ES hosts"

---

py-utils/src/utils/kv_store/kv_store.py
py-utils/src/utils/kv_store/kv_store_collection.py
py-utils/test/test_conf_store/test_conf_sample_json.json
py-utils/test/test_kv_store/conf_sample_json.json
py-utils/test/test_kv_store/test_kv_store.py

Integrated KvData, IniKvData and  DictKvData classes
Added testcases.

Ini file fix

---

py-utils/src/utils/service.py

EOS-16519 : Adding common utils functions

---

py-utils/setup.py
py-utils/src/utils/setup/__init__.py
py-utils/src/utils/setup/setup_cli.py
py-utils/src/utils/setup/utils.py

Enhance setup script to support post_install, config, test phases

setup script for Mini provisioner for cortx-py-utils

---

statsd-utils/jenkins/stats_utils.spec

Update URL path from old internal GitLab URL to latest GitHub URL to fix https://github.com/Seagate/cortx-utils/issues/175

Update URL path from old internal GitLab URL to latest GitHub URL

---

py-utils/src/utils/kv_store/kv_store_collection.py
py-utils/src/utils/schema/format.py
py-utils/src/utils/schema/payload.py

The imports modules has been moved from usual top lines to methods
where they are actually used.

Implementing lazy imports for json, toml and yaml modules

---

py-utils/requirements.txt

Use cryptography 2.8 python package.

Use cryptography version 2.8

---

py-utils/requirements.txt

Signed-off-by: Sachin Punadikar <sachin.punadikar@seagate.com>

Correct the version of numpy package

---

py-utils/src/utils/message_bus/message_broker_collection.py
py-utils/src/utils/message_bus/message_bus.py
py-utils/src/utils/message_bus/message_bus_client.py
py-utils/test/test_message_bus/test_unread_count.py

Gets the count of unread messages from MessageBus

---

py-utils/src/utils/message_bus/message_broker_collection.py

Removing pandas for data processing of get_unread_count

---

py-utils/src/utils/message_bus/message_broker_collection.py
py-utils/src/utils/message_bus/message_bus.py
py-utils/src/utils/message_bus/message_bus_client.py
py-utils/test/test_message_bus/test_list_message_type.py

API to list existing message types

---

py-utils/setup.py

Signed-off-by: rahul tripathi <rahul.tripathi@seagate.com>

Add kafka setup directory package list in setup.py

---

py-utils/src/utils/message_bus/message_broker_collection.py

MessageBus: Throw error if Kafka Broker is down

---

py-utils/src/setup/msg_bus_test.py

Removing consumer.ack from message_bus_test

---

py-utils/src/setup/utils.py

Checking whether zookeeper and kafka services are running - post_install phase

---

py-utils/src/utils/process.py

Adding support for PipedProcess

---

py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py

In utils_setup reset phase - Delete any existing message types (Kafka Topics)
In utils_setup cleanup phase - Remove /etc/cortx/message_bus.conf file
Jira ticket ID - https://jts.seagate.com/browse/EOS-19737

EOS-19737: Support for Reset & Cleanup phase in utils_Setup

---

py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py

Reverts Seagate/cortx-utils#274

Revert "EOS-19737: Support for Reset & Cleanup phase in utils_Setup"

---

py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py
py-utils/src/utils/errors.py

This provides support for Reset/Cleanup for utils_setup
Associated jira - https://jts.seagate.com/browse/EOS-19737

EOS-19737 : Added Reset/Cleanup for utils_setup

---

py-utils/setup.py
py-utils/src/utils/errors.py
py-utils/src/utils/iem_framework/__init__.py
py-utils/src/utils/iem_framework/error.py
py-utils/src/utils/iem_framework/event_message.py
py-utils/src/utils/message_bus/__init__.py
py-utils/src/utils/message_bus/cortx_message_bus.service
py-utils/src/utils/message_bus/error.py
py-utils/src/utils/message_bus/message_broker_collection.py
py-utils/src/utils/message_bus/message_bus_server.py
py-utils/src/utils/rest_server/__init__.py
py-utils/src/utils/rest_server/error.py
py-utils/src/utils/rest_server/rest_server.py
py-utils/src/utils/service/service_handler.py
py-utils/test/iem_framework/test_iem.py
py-utils/test/test_message_bus/test_rest_server.py
py-utils/test/test_service_handler.py

Merge tmain into main

---

py-utils/src/setup/utils.py
py-utils/src/utils/errors.py
py-utils/src/utils/message_bus/error.py
py-utils/src/utils/message_bus/message_broker.py
py-utils/src/utils/message_bus/message_broker_collection.py
py-utils/src/utils/message_bus/message_bus.py
py-utils/src/utils/message_bus/message_bus_client.py

- Msgbus should send appropriate Error Codes for failures scenarios
-  JIRA [EOS-19829](https://jts.seagate.com/browse/EOS-19829)
-  [MessaseBus_specification](https://seagatetechnology.sharepoint.com/:w:/r/sites/gteamdrv1/tdrive1224/_layouts/15/doc2.aspx?sourcedoc=%7Bf6e8668a-6730-41b9-af1c-bde466ac4157%7D&action=edit&wdPid=7f42c77a)

EOS-19829: Msgbus should send appropriate Error Codes for failures scenarios

---

py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py
py-utils/src/utils/log.py

- utils_setup should log its activity
-  JIRA - [EOS-19858](https://jts.seagate.com/browse/EOS-19858)

EOS-19858: utils_setup should log its activity

---

py-utils/src/utils/conf_store/conf_cli.py
py-utils/test/conf_store/test_conf_cli.py

- ConfStore: Support "merge" option in conf CLI
-  [EOS-21062](https://jts.seagate.com/browse/EOS-21062)

EOS-21062: ConfStore: Support "merge" option in conf CLI

---

py-utils/setup.py
py-utils/src/utils/iem_framework/iem_cli.py
py-utils/test/iem_framework/message_file.json
py-utils/test/iem_framework/test_iem_cli.py
py-utils/test/setup.py

- Create a cli for IEM framework
- [IEM Framework Confluence Link](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/316735500/IEM+Framework)
- [JIRA EOS-17754 link](https://jts.seagate.com/browse/EOS-17754)
- Coding conventions are followed and code is consistent [Y/N]: Y
- Confirm All CODACY errors are resolved [Y/N]: Y

EOS-17754: Adding cli for IEM alert

---

py-utils/README.md

Added root(sudo) permission in READ.md
- Error in building and installing without root permission
-  https://github.com/Seagate/cortx-utils/issues/342
-  Coding conventions are followed and code is consistent [Y/N]: NA

Added root permission for build, install and uninstall

---

py-utils/src/utils/setup/openldap/openldap.py

- Implements the steps for prepare and init phase of openldap provisioning as defined in the [HLD](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/268829518/OpenLDAP+in+CORTX+Environment).
-  Redesign of keys validation logic and calling the same from prepare and init phase as per [HLD](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/268829518/OpenLDAP+in+CORTX+Environment).
-  [x] Coding conventions are followed and code is consistent. 
-  [x] Confirm All CODACY errors are resolved.

Implementation of prepare and init phases, redesign of keys validation logic.

---

py-utils/README.md

Reverts Seagate/cortx-utils#350
-----
[View rendered py-utils/README.md](https://github.com/Seagate/cortx-utils/blob/revert-350-update_py_utils_README/py-utils/README.md)

Revert "Added root permission for build, install and uninstall"

---

jenkins/build.sh

Signed-off-by: Udayan Yaragattikar <udayan.yaragattikar@seagate.com>

Bugfix for main build failure

---

py-utils/src/setup/setup.yaml
py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py

- Provide a blank hook for post/pre upgrade which can be utilized for implementation when required
-  [Mini Provisioner Link](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/313426367/Mini-Provisioner+Specifications
)

EOS-20335 Provide post/pre upgrade hooks 

---

py-utils/src/setup/utils.py
py-utils/src/utils/message_bus/message_bus.py

EOS-22091: Fix for MessageBus log file to allow log entries by any user

---

py-utils/README.md

-----
[View rendered py-utils/README.md](https://github.com/selvakumaar5496/cortx-utils/blob/readme/py-utils/README.md)

Remove pip installation steps

---

py-utils/utils-post-install

Signed-off-by: Mohammed Shahid <mohammed.shahid@seagate.com>
- openldap_setup binary was not getting generated
-  Added code to relevant script to generate this.
-  [x] Coding conventions are followed and code is consistent.
-  [ ] Confirm All CODACY errors are resolved. 

Add code to copy the openldap_setup.py as openldap_setup binary.

---

py-utils/src/utils/log.py

- Need to add process id in logger format
```
2021-07-08 09:33:12 40016 message_bus INFO [__init__] MessageBus initialized as$
2021-07-08 09:35:45 45825 message_bus INFO [__init__] MessageBus initialized as$
2021-07-08 09:40:55 9216 message_bus INFO [__init__] MessageBus initialized as $
2021-07-08 09:41:47 11076 message_bus INFO [__init__] MessageBus initialized as$
2021-07-08 09:42:35 12513 message_bus INFO [__init__] MessageBus initialized as$
```

EOS-22300: Added Process id in logger format

---

py-utils/src/utils/data/db/consul_db/storage.py
py-utils/src/utils/data/db/db_provider.py
py-utils/src/utils/data/db/elasticsearch_db/storage.py

Generic db index creation changes - Addressed review comments

---

py-utils/setup.py
py-utils/src/utils/setup/openldap/openldap.py
py-utils/src/utils/setup/openldap/openldapsetup_prereqs.json
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.1-node

- Init phase for openldap validation missing key fixes.
-  Modify call to validate services. 

EOS-19840 - init phase validation fixes.

---

py-utils/src/utils/data/access/queries.py
py-utils/src/utils/data/db/consul_db/storage.py
py-utils/src/utils/data/db/db_provider.py
py-utils/src/utils/data/db/elasticsearch_db/storage.py

- Problem statement 1. Sorting is not working with text fields in ES. 2. s3-rsys-index should not be generated through generic DB framework.
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/494600216/Rsyslog+and+Elasticsearch
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/486114207/Elasticsearch-+Sorting+on+text+fields

EOS-21195: Feature audit logs

---

py-utils/src/utils/setup/openldap/base_configure_ldap.py
py-utils/src/utils/setup/openldap/setupReplication.py

Formatting changes suggested by Selva

---

py-utils/src/utils/discovery/error.py
py-utils/src/utils/discovery/resource_map.py

-- Adding Resource Map in Cortx Utils
- Improvement code.
-  This framework code will be used across all components when required. It is a generic common code.

EOS-17458 : CortxV2 SSPL: Enhance System Manifest

---

py-utils/src/utils/setup/openldap/openldap.py
py-utils/src/utils/setup/openldap/openldap_prov_config.yaml
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.1-node
py-utils/src/utils/setup/openldap/test.py

eos23041-Config phase validations

---

py-utils/src/utils/setup/openldap/test.py

Logging fix for TEST phase

---

py-utils/src/utils/setup/openldap/openldap.py

EOS23109 Validation message is not specific

---

py-utils/src/utils/setup/openldap/base_configure_ldap.py
py-utils/src/utils/setup/openldap/setupcmd.py

Config command issue fixed
Fixed the index name of config file 
[OpenldapProvisioning.log](https://github.com/Seagate/cortx-utils/files/6876379/OpenldapProvisioning.log)

Config command issue fixed

---

py-utils/src/utils/setup/openldap/configcmd.py
py-utils/src/utils/setup/openldap/openldap.py

Enabling openldap replication 

---

py-utils/src/utils/setup/openldap/base_configure_ldap.py
py-utils/src/utils/setup/openldap/cleanupcmd.py
py-utils/src/utils/setup/openldap/openldap.py

Signed-off-by: Mohammed Shahid <mohammed.shahid@seagate.com>
- Implement cleanup phase for openldap provisioning
- Cleanup phase details are implemented as per design
-  [ ] Coding conventions are followed and code is consistent. 
-  [ ] Confirm All CODACY errors are resolved.

EOS-19842 : Openldap provisioning - Cleanup phase implementation

---

py-utils/src/utils/setup/openldap/openldap.py

EOS 23126-Performing server_nodes validation irrespective of node count

---

py-utils/src/utils/setup/openldap/openldap.py
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.1-node

TEST phase template change

---

py-utils/src/utils/setup/openldap/cleanupcmd.py
py-utils/src/utils/setup/openldap/openldap.py
py-utils/src/utils/setup/openldap/openldap_setup.py
py-utils/src/utils/setup/openldap/resetcmd.py
py-utils/src/utils/setup/openldap/setup.yaml

Signed-off-by: Mohammed Shahid <mohammed.shahid@seagate.com>
- Hardening reset and cleanup validations
-  Fix testing bugs. 

EOS-23202 : Cleanup, reset phase and other misc bug fixes.

---

py-utils/src/utils/setup/openldap/openldap.py
py-utils/src/utils/setup/openldap/openldap_setup.py
py-utils/src/utils/setup/openldap/openldapsetup_prereqs.json
py-utils/src/utils/setup/openldap/postupgradecmd.py
py-utils/src/utils/setup/openldap/preupgradecmd.py
py-utils/src/utils/setup/openldap/setup.yaml
py-utils/src/utils/setup/openldap/setupcmd.py

Implementation of upgrade interface for openldap mini provisioner
Implement Pre upgrade interface
Implement Post upgrade interface
Upgrade py-utils rpm
[OpenldapProvisioning.log](https://github.com/Seagate/cortx-utils/files/6892228/OpenldapProvisioning.log)

EOS-23136: Upgrade Framework changes

---

py-utils/src/utils/setup/openldap/cleanupcmd.py
py-utils/src/utils/setup/openldap/openldap.py
py-utils/src/utils/setup/openldap/resetcmd.py

- File truncation replaces deletion.
-  Log file should be emptied after reset and cleanup but not deleted.

EOS-23202 - reset and cleanup fixes

---

py-utils/src/utils/support_framework/model.py
py-utils/src/utils/support_framework/support_bundle.py

- Support Bundle: get_status of all bundles
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework

EOS-22816 : Support Bundle: get_status of all bundles

---

py-utils/src/utils/setup/openldap/base_configure_ldap.py
py-utils/src/utils/setup/openldap/openldap_prov_config.yaml

Moving policy schema to base config

---

py-utils/src/utils/setup/openldap/base_configure_ldap.py
py-utils/src/utils/setup/openldap/cleanupcmd.py

EOS-22326 CleanUp phase not clearing cn-config password LDAP

---

py-utils/src/utils/setup/openldap/openldapsetup_prereqs.json

- Migrate from openldap to symas-openldap 
-  Change the pre-requisite validation to check for symas-openldap instead of openldap

EOS-22325 : updates to support symas-openldap (validations)

---

py-utils/src/setup/utils.py

- Enhance Cleanup n Reset phases for utils_setup.
- reset: After reset all the user related data should be deleted (All messages in MB and IEMS)
- cleanup: After cleanup all the user related data and all the configuration should be deleted (All messages and topics)
-  [https://jts.seagate.com/browse/EOS-22981](https://jts.seagate.com/browse/EOS-22981)

EOS-22981: Enhanced reset and cleanup

---

py-utils/src/utils/support_framework/__init__.py
py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/support_framework/errors.py
py-utils/src/utils/support_framework/services.py
py-utils/src/utils/support_framework/support_bundle.py

- Code changes to trigger to utils bundle_generate
-  https://jts.seagate.com/browse/EOS-23391

EOS-23391: Code changes to trigger to utils bundle_generate

---

py-utils/src/utils/support_framework/bundle.py
py-utils/src/utils/support_framework/support_bundle.py

integrate shared path and merge tar files from all node into one common tar
if shared path is available, all nodes create support bundle in <shared_path/bundle_id/bundleid_hostname.tar.gz>
once support bundle generation is done, all the bundle are merged into one 
<shared_path/bundle_id/bundleid.tar.gz>

EOS-23298: integrate shared path and merge tar files from all node into one

---

jenkins/code_coverage/code_coverage.sh
renovate.json

- Code coverage: To validate the code over unittest test cases
-  https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/135397543/Code+Coverage+Practices

EOS-22828: Add code coverage script

---

py-utils/src/utils/data/db/examples/openldap/openldap_storage.py
py-utils/src/utils/data/db/openldap/storage.py

- [EOS-22626](https://jts.seagate.com/browse/EOS-22626): Add CRUD functionalities for Openldap.
-  https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/584384987/F-45J+OpenLdap+in+cortx-utils+data+framework

EOS-22626: Integrate OpenLdap into the Generic database framework

---

py-utils/src/setup/templates/utils.config.tmpl.1-node
py-utils/src/setup/templates/utils.config.tmpl.3-node
py-utils/src/setup/templates/utils.post_install.tmpl.1-node
py-utils/src/setup/templates/utils.post_install.tmpl.3-node
py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py
py-utils/src/utils/shared_storage/shared_storage.py
py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/support_framework/support_bundle.py

- Enhancements while integrating SB
-  https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework

Enhancements for Support Bundle Integration

---

py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/support_framework/support_bundle.py

- These changes addresses the issues for integration of support bundle framework
-  https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework

Support bundle framework integration

---

py-utils/README.md

Signed-off-by: Patrick Hession <patrick.hession@seagate.com>
Removed unnecessary '$' symbols
Fixed broken directory traversal commands
- Commands to change directories do not work 
- [Y ] Confirm that Test Cases are added (for both the cases, fix and feature) [Y/N]: 
- [Y ] PR is self reviewed
- [Y ] Check if the description is clear and explained. 
- [ Y] Check Acceptance Criterion is defined. 
- [Y ] Changes done to WIKI / Confluence page
Fixes #447 
-----
[View rendered py-utils/README.md](https://github.com/hessio/cortx-utils/blob/main/py-utils/README.md)

Updated directory traversal commands

---

py-utils/src/utils/support_framework/support_bundle.py
py-utils/src/utils/support_framework/support_bundle.yaml

- These changes addresses the issues for integration of support bundle framework
-  https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework

Support bundle improvement

---

py-utils/src/utils/setup/openldap/setupReplication.py
py-utils/src/utils/setup/openldap/setupcmd.py
py-utils/src/utils/setup/openldap/test.py

eos23559- codacy fixes

---

py-utils/src/utils/setup/openldap/configcmd.py
py-utils/src/utils/setup/openldap/openldap.py
py-utils/src/utils/setup/openldap/openldap_setup.py
py-utils/src/utils/setup/openldap/preupgradecmd.py
py-utils/src/utils/setup/openldap/resetcmd.py

Signed-off-by: Mohammed Shahid <mohammed.shahid@seagate.com>
- Fixing codacy issues for feature branch.
-  Generic codacy fixes.

EOS-23559 : Fixing codacy issues for feature branch.

---

py-utils/README.md

- Broken codacy badge in py-utils directory
-  Codacy badge is not required in py-utils directory. Its already present at the root of the repo
-  Coding conventions are followed and code is consistent [Y/N]: NA
-  Confirm All CODACY errors are resolved [Y/N]: NA
-----
[View rendered py-utils/README.md](https://github.com/sachinpunadikar/cortx-utils/blob/codacy-badge/py-utils/README.md)

Remove codacy badge in py-utils directory

---

py-utils/src/utils/data/db/examples/openldap/openldap_storage.py
py-utils/src/utils/data/db/openldap/storage.py

- [EOS-22632](https://jts.seagate.com/browse/EOS-22632)
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/584384987/F-45J+OpenLdap+in+cortx-utils+data+framework

EOS-22632: Implement the 'count' method for OpenLdap

---

py-utils/setup.py
py-utils/src/utils/manifest/__init__.py
py-utils/src/utils/manifest/manifest_support_bundle.py

Improvement task.
--> Added manifest generate interface
--> Added manifest get_status interface

EOS-22367:Bundle R2 Manifest in Support Bundle (generate, get_status)

---

py-utils/setup.py
py-utils/src/utils/support_framework/bundle_generate.py

- Integrated the manifest support bundle generation script with the support framework.
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework 

EOS-23637: Manifest integration

---

py-utils/src/support/support_bundle_cli.py
py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/support_framework/model.py
py-utils/src/utils/support_framework/support_bundle.py
py-utils/test/support_bundle/test_support_bundle.py

- Support bundle is not generated for all the components.
- BUG
-  https://jts.seagate.com/browse/EOS-23332
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework

EOS-23332: BUG-Support bundle is not generated for all the components.

---

py-utils/setup.py
py-utils/src/utils/setup/openldap/base_configure_ldap.py
py-utils/src/utils/setup/openldap/iam-constraints.ldif
py-utils/src/utils/setup/openldap/ppolicy-default.ldif
py-utils/src/utils/setup/openldap/ppolicymodule.ldif
py-utils/src/utils/setup/openldap/ppolicyoverlay.ldif

Data was hardcoded/pasted inside py script. As  a result- code was not looking clean 
Used ldif package from python-ldap and instead of hardcoding data , read the data from ldifs directly

EOS23627 - Implement ldifParser and remove data hardcoding

---

py-utils/src/utils/data/db/openldap/storage.py

- [EOS-23899](https://jts.seagate.com/browse/EOS-23899)
- Updating object on 'store' enables generic database framework to feel like any other ORM framework and makes it more convenient.
-  If the user is trying to store object that already exists, update the object with provided new attributes.

EOS-23899: update object when storing if it exists in OpenLdap

---

py-utils/src/utils/setup/openldap/openldap.py
py-utils/src/utils/setup/openldap/openldap_prov_config.yaml
py-utils/src/utils/setup/openldap/setupcmd.py
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.1-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.3-node
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.3-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.1-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.3-node
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.3-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.1-node.sample
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.3-node
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.3-node.sample
py-utils/src/utils/setup/openldap/test.py

1.Password hardcoded in TEST phase
2.Unwanted fields present in config and test phases
Removed password hardcoding and unwanted fields and corrected templates

EOS-23882 - Remove hardcoded password from Test phase

---

py-utils/src/setup/utils.py

EOS-23332: update local path key

---

py-utils/test/iem_framework/test_iem_cli.py

- correction in test from "severity from Critical to critical" based on confluence [Link](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735500/IEM+Framework#Details-on-Severity)
- change in spelling

changed severity in iem message from 'Critical' to 'critical'

---

py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.config.tmpl.3-node
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.init.tmpl.3-node
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.1-node
py-utils/src/utils/setup/openldap/templates/openldap.test.tmpl.3-node

Template Change to add quotes
Added quotes wherever required

Updating template files to add quotes

---

py-utils/src/utils/support_framework/support_bundle.yaml

- Changed setup.yaml to support.yal for ha and hare components in support_bundle.yaml
-  https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework

Changed setup.yaml to support.yaml for ha and hare components in support_bundle.yaml

---

py-utils/src/utils/setup/kafka/kafka.post-install.conf.tmpl
py-utils/src/utils/setup/kafka/kafka.py
py-utils/src/utils/setup/kafka/kafka_setup.py

- Init phase syntax error removed

fix for init phase of kafka_setup

---

py-utils/src/support/utils_support_bundle.py
py-utils/src/utils/manifest/manifest_support_bundle.py

- Added directories to utils and manifest in SB generation
-  https://jts.seagate.com/browse/EOS-24206

EOS-24206: Added directories to utils and manifest in SB generation

---

py-utils/src/utils/setup/__init__.py

kafka setup failing because of openldap import for python-ldap package
Removed reference of openldap import

EOS-24238 kafka setup failing

---

py-utils/src/utils/support_framework/support_bundle.yaml

- Added support.yaml to SSPL component
-  NA

Added support.yaml to SSPL component

---

py-utils/src/setup/utils.py

- fix for post_install_teplate not working

post_install_template fix

---

py-utils/src/utils/setup/openldap/openldap.py

Proper error message were not getting displayed
Fixed the message texts and handled one field missing scenario.

EOS24097-Error message not proper

---

py-utils/cortx.conf.sample

- Adding support local_path to .sample file
-  Adding support local_path to .sample file

Adding support local_path to .sample file

---

py-utils/src/utils/setup/kafka/kafka.py

log location changes
kafka log :         /var/log/kafka           -> /var/lib/kafka
changed kafka log path to /var/lib/kafka

Change kafka and zookeeper log directory

---

jenkins/build.sh
py-utils/utils-post-uninstall

- Added install_path for utils_post_uninstall
-  install_path is defined in build script and will be sourced to uninstall script

Added install path to utils-post-uninstall

---

py-utils/cortx.conf.sample
py-utils/setup.py
py-utils/src/utils/errors.py
py-utils/src/utils/solution/__init__.py
py-utils/src/utils/solution/lr2/__init__.py
py-utils/src/utils/solution/lr2/server/__init__.py
py-utils/src/utils/solution/lr2/server/manifest.py
py-utils/src/utils/solution/lr2/server/server_resource_map.py
py-utils/src/utils/solution/lr2/service/__init__.py
py-utils/src/utils/solution/lr2/service/software.py
py-utils/src/utils/solution/lr2/storage/__init__.py
py-utils/src/utils/solution/lr2/storage/storage_resource_map.py
py-utils/utils-post-install

- [SPIKE] Generate Manifest for Software alone 

EOS-23497: [SPIKE] Generate Manifest for Software alone

---

py-utils/src/utils/support_framework/bundle_generate.py

- Added Log.init to bundle_generate to log message and logging to status
-  NA

Added logging to status

---

py-utils/test/README.md

- Updating README under test directory with a list of test scripts that perform SSH to verify functionalities.
-  Add a disclaimer in README under test directory with a list of test scripts that perform SSH to verify py-utils functionalities.
-----
[View rendered py-utils/test/README.md](https://github.com/veerendra-simha-garikipati/cortx-utils/blob/test_readme_update/py-utils/test/README.md)

Updating README under test directory with a list of test scripts that perform SSH

---

py-utils/test/setup.py
py-utils/test/support_bundle/config.yaml
py-utils/test/support_bundle/test_support_bundle.py
py-utils/test/support_bundle/test_support_bundle_cli.py

-  Support bundle test automation, Adding unittests
-  TD: https://jts.seagate.com/browse/EOS-23451
-  TA: https://jts.seagate.com/browse/EOS-24159
-  TE: https://jts.seagate.com/browse/TEST-27065

Adding SB unittests

---

py-utils/src/utils/setup/kafka/kafka.py
py-utils/src/utils/setup/kafka/kafka_setup.py

-  Kafka mini provisioning, cleanup and reset phase
- Implemented kafka cleanup and reset phase

EOS-24547: kafka miniprovisioning reset and cleanup phase

---

py-utils/src/setup/templates/utils.config.tmpl.1-node
py-utils/src/setup/templates/utils.config.tmpl.3-node
py-utils/src/setup/templates/utils.post_install.tmpl.1-node
py-utils/src/setup/templates/utils.post_install.tmpl.3-node
py-utils/src/setup/utils.py
py-utils/src/utils/message_bus/message_broker.py

- Accommodate new/changed config keys in kubernetes environment
-  https://jts.seagate.com/browse/EOS-24357

EOS-24357: Accommodate new/changed config keys in kubernetes environment

---

py-utils/src/utils/schema/database.py
py-utils/src/utils/support_framework/bundle_generate.py

- Added 'create schema' database.py for 3Node status
- Status is not getting for multiple nodes
- NA

Added 'create schema' database.py for multi node status

---

py-utils/src/setup/utils.py

- iem directory correction
-  config  phase getting failed due to incorrect iem log dir

iem_log issue in mini provisioning config

---

py-utils/src/utils/log.py

- Cortx setup requires logging messages in both console and log files.
- Enable/Disable console output for log message from cortx_utils log module.

EOS-24902: cortx_utils: Enable log message in console

---

py-utils/src/utils/setup/consul/consul_prvsnr.py

- Watcher scripts invoked with root user will fail if service is running with consul user
-  Run consul service with root user

EOS-22576: Run consul service with root user

---

py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/support_framework/support_bundle.py

- Support bundle error issue
-  https://jts.seagate.com/browse/EOS-25028

EOS-25028: Support bundle error issue

---

py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py

- https://jts.seagate.com/browse/EOS-25061
-  Remove argv from function call 

EOS-25061: Execute utils_setup as a binary

---

py-utils/src/setup/utils.py

Remove unwanted code from utils_setup 

---

py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/support_framework/support_bundle.py

- Added f-string for error messages in Support Bundle
-  NA

Added f-string for error messages in Support Bundle

---

py-utils/cortx.conf.sample
py-utils/src/setup/utils.py
py-utils/src/support/support_bundle_cli.py
py-utils/src/utils/iem_framework/event_message.py
py-utils/src/utils/shared_storage/shared_storage.py
py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/support_framework/support_bundle.py

- Change format of cortx.conf.sample to yaml.
- Entier utils code updated consistent to be yaml.

EOS-25063: Change conf file format to yaml

---

py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py
py-utils/src/utils/message_bus/message_broker.py
py-utils/src/utils/message_bus/message_bus.py
py-utils/src/utils/utils_server/utils_server.py

- Inconsistent use of file format /etc/cortx/cortx.conf
-  use file format consistently

Consistent use of file format /etc/cortx/cortx.conf

---

py-utils/src/utils/setup/openldap/openldap.py
py-utils/src/utils/setup/openldap/openldap_prov_config.yaml
py-utils/src/utils/setup/openldap/templates/openldap.cleanup.tmpl

INstall dir and data dir not getting cleaned
New parameters to cleanup added

Adding new parameters to cleanup phase

---

py-utils/src/setup/utils.py

Signed-off-by: Rahul Tripathi rahul.tripathi@seagate.com
- _set_to_conf_file was made non static. this needs to be fixed
-  made _set_to_conf_file as static method again.

Made _set_to_conf_file as static

---

py-utils/src/setup/__init__.py
py-utils/src/setup/utils_setup.py

- imports in setup package was throwing error while mini provisioning
-  Removed unnecessary imports in __init__.py 

utils setup package ini import fix

---

py-utils/src/utils/iem_framework/event_message.py

- IEM test cases were failing
-  Separated the initialization of logger from init method

EOS-25090: Fix test cases: Separated logger init to another static method.

---

py-utils/test/cli_framework/test_cli_framework.py
py-utils/test/consul/test_consul.py
py-utils/test/elasticsearch/test_elasticsearch.py
py-utils/test/support_bundle/test_support_bundle.py
py-utils/test/support_bundle/test_support_bundle_cli.py
py-utils/test/test_service_handler.py
py-utils/test/validator/test_consul_validator.py
py-utils/test/validator/test_elasticsearch_validator.py
py-utils/test/validator/test_path_validator.py
py-utils/test/validator/test_pkg_validator.py
py-utils/test/validator/test_service_validator.py

- Fixed py-utils failing unittests mentioned in EOS-25091
-  https://jts.seagate.com/browse/EOS-25091

py-utils unittest fix's

---

py-utils/src/utils/validator/v_network.py

Network connectivity reported ping failure on controller IP.
Intermittent packet loss(LRL-2440) seen when count is 1 and wait time is 1 sec.
**Test Result Link:**
https://jts.seagate.com/browse/EOS-24010?focusedCommentId=2213590&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2213590

EOS-24010: Intermittent ping failure with packet count 1

---

py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py
py-utils/src/support/support_bundle_cli.py
py-utils/src/utils/common/common.py
py-utils/src/utils/discovery/request_handler.py
py-utils/src/utils/iem_framework/event_message.py
py-utils/src/utils/iem_framework/iem_cli.py
py-utils/src/utils/message_bus/message_broker.py
py-utils/src/utils/message_bus/message_bus.py
py-utils/src/utils/message_bus/message_bus_client.py
py-utils/src/utils/setup/openldap/setupcmd.py
py-utils/src/utils/shared_storage/shared_storage.py
py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/support_framework/const.py
py-utils/src/utils/support_framework/support_bundle.py
py-utils/src/utils/utils_server/utils_server.py
py-utils/test/discovery/test_discovery.py

- The cluster.conf file (master file containing CORTX cluster info) should not be assumed at fixed location
-  This change is as per the guidelines on accepting cluster.conf file as an input to various services. 

Accept dynamic location for cluster.conf

---

py-utils/src/utils/support_framework/support_bundle.yaml

CSM component's support.yaml needs modification as there will be no cortxcli installed in  k8s environment
CSM component's support.yaml modified

CSM component support.yaml path modified.

---

.whitesource
whitesource.config

This update contains, adding 2 files related to whitesource configuration
1 - .whitesource.
2 - whitesource.config
To enable whitesource scans.
Corresponding bug is raised in JIRA
JIRA Bug -> https://jts.seagate.com/browse/EOS-25946
-  Confirm All CODACY errors are resolved [Y/N]:  NA
Not Applicable.
These changes are tested on other repositories.
Not Applicable

Update to whitesource configuration to enable scan

---

py-utils/src/utils/conf_store/conf_cache.py
py-utils/src/utils/conf_store/conf_cli.py
py-utils/src/utils/conf_store/conf_store.py
py-utils/src/utils/kv_store/kv_payload.py
py-utils/src/utils/kv_store/kv_store.py

ConfStore: search functionality based on key and value
-  Added Search API in the constore based on key and value
Tested the changes with the custom build on kubernetes 
http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.9/job/cortx-all-image-custom-ci/1227/

ConfStore: search functionality based on key and value

---

py-utils/src/utils/kv_store/kv_store_collection.py

- when wrong consul endpoint is provided in conf store, a proper kverror with pretty message is needed
-  added exception handling in case of exception and raised kverror instead
New exception Traceback:
.
.
.
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='consul-server.default.svc.cluster.local', port=8): Max retries exceeded with url: /v1/kv/?keys=True (Caused by …

EOS-26741: Raise KVError when connection refused for consul

---

py-utils/src/support/cortx_support_bundle.py
py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/support_framework/support_bundle.py

Signed-off-by: Palak Garg <palak.garg@seagate.com>
- Accept SB Filters - Components, binlogs, coredumps, stacktrace etc
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/749076684/Node+level+Support+Bundle+Collection

EOS-26683: Accept SB Filters - Components, binlogs, stacktrace etc

---

py-utils/src/support/cortx_support_bundle.py

Signed-off-by: Palak Garg <palak.garg@seagate.com>
- Update the default value to False for binlogs filter.
- Update the default value to False for binlogs filter.
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/749076684/Node+level+Support+Bundle+Collection

Update Include binlogs default value to False

---

py-utils/src/setup/utils.py
py-utils/src/utils/message_bus/message_broker.py
py-utils/src/utils/message_bus/message_broker_collection.py
py-utils/src/utils/message_bus/message_bus.py
py-utils/test/message_bus/test_message_bus.py

- Read the passed in config using MessageBus.init() method
-  https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/349307984/CORTX+Message+Bus

EOS-25892: Implement MessageBus.init()

---

py-utils/src/utils/cortx/const.py

Signed-off-by: Rahul Tripathi rahul.tripathi@seagate.com
- changed double quotes to single quotes as per utils coding convention
- Single quotes for single word, as per Utils coding convention.

updating quotes as per coding convention in const.py

---

py-utils/src/utils/support_framework/log_filters.py

- Provide a general interface to Optimize Support Bundle Size
-  SB Framework will provide a general interface for the components to use to limit the size of the log file to be collected. 
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/749076684/Node+level+Support+Bundle+Collection

EOS-25997: Implement limit_size API

---

py-utils/src/utils/message_bus/message_bus_server.py
py-utils/test/message_bus/test_message_bus_server.py

- To accommodate message bus init changes updated the message bus server code.

EOS-26899: Message server changes for init argument

---

py-utils/test/message_bus/test_message_bus.py

- MessageBus testcase failed
- Add testcase for MessageBus.init()

Add MessageBus.init() in testcase

---

py-utils/src/setup/utils.py
py-utils/src/utils/message_bus/message_broker.py
py-utils/src/utils/message_bus/message_broker_collection.py
py-utils/src/utils/message_bus/message_bus.py
py-utils/src/utils/message_bus/message_bus_client.py
py-utils/src/utils/message_bus/message_bus_server.py
py-utils/test/message_bus/test_message_bus.py
py-utils/test/message_bus/test_message_bus_server.py

Reverts Seagate/cortx-utils#644

Revert "MessageBus library code should not refer any conf file"

---

py-utils/src/utils/support_framework/log_filters.py

- accept duration in format 2020-09-06T05:30:00P5DT3H3S

EOS-25756: implementation for log filtering based on duration

---

py-utils/src/utils/audit_log/audit_log_server.py
py-utils/src/utils/utils_server/utils_server.py

- S3 Audit Log: Expose an API to push audit logs
- Changed method name receive to send as consistency
-  https://jts.seagate.com/browse/EOS-26021

EOS-26021: S3 Audit Log: Expose an API to push audit logs(method name change)

---

py-utils/src/setup/utils.py
py-utils/test/message_bus/test_kvpayload_message.py
py-utils/test/message_bus/test_message_bus.py

- Init phase of utils Mini Provisioning failed
-  Fix init phase of utils Mini Provisioning 

Fix init phase of Miniprovisioning

---

py-utils/src/utils/log.py
py-utils/src/utils/message_bus/message_bus.py

- Ignore logging if logger is not initialised
-  https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/349307984/CORTX+Message+Bus 

Ignore logging in message_bus if logger is not initialised

---

py-utils/python_requirements.txt

PyYAML package version needs to be upgraded to 5.4.1
JIRA Bug -> https://jts.seagate.com/browse/EOS-23696
-  Coding conventions are followed and code is consistent [Y/N]: Y (Just a reference to python_requirements.txt)
-  Confirm All CODACY errors are resolved [Y/N]: Not applicable
Following testing is conducted
- Code changes made to all the repositories (including cortx-utils) on a fork
- It was build, and deployed on single node cortx-k8s cluster
- It was tested with automated sanity test suite
- It was tested for basic aws client operations
- Detailed test results are uploaded on JIRA Bug here -> https://jts.seagate.com/browse/EOS-23696 …

Upgrade PyYAML version to 5.4.1

---

py-utils/python_requirements.txt

Reverts Seagate/cortx-utils#662

Revert "Upgrade PyYAML version to 5.4.1"

---

py-utils/python_requirements.txt

Signed-off-by: Swanand S Gadre <swanand.s.gadre@seagate.com>
PyYAML package needs to be upgraded to 5.4.1
JIRA reference -> https://jts.seagate.com/browse/EOS-23696
-  Coding conventions are followed and code is consistent [Y/N]: Not applicable
-  Confirm All CODACY errors are resolved [Y/N]: Not applicable
Change is to update version from 5.1.2 to 5.4.1
Following testing is conducted
Testing conducted as follows
- Code changes were made on all the repositories by creating forks.
- Then it was built and deployed on single node cortx-k8s cluster
- Then it was tested with automated sanity test
- It was also tested for basic aws cli commands …

Upgrade PyYAML package to 5.4.1

---

py-utils/src/utils/kv_store/kv_payload.py
py-utils/src/utils/kv_store/kv_store_collection.py

- ConfStore's Search API is not implemented for consul kv backend,
-  Implemented search api for consul kv ConfStore backend

EOS 27049 consul search

---

py-utils/python_requirements.txt

- Upgrade PyYAML version from 5.1.2 to 5.4.1

PATCH: update PyYaml version

---

.whitesource

Add whitesource configuration
Need to enable whitesource configuration.
Existing configuration is overwritten after making kubernetes as main branch.
https://jts.seagate.com/browse/EOS-26134
Testing will be covered as part of PR approval
Not applicable

Add whitesource configuration

---

py-utils/src/support/utils_support_bundle.py

- Filters support for Support bundle creation for Utils
-  https://jts.seagate.com/browse/EOS-26183

EOS-26183: Filters support for Support bundle creation for Utils

---

py-utils/src/utils/cortx/const.py

- Add new component name - 'cclient' and service 'cclient_service' in const.py

EOS-27086: Add cclinet component and service name in const.py

---

py-utils/src/utils/message_bus/message_broker.py
py-utils/src/utils/message_bus/message_bus.py
py-utils/src/utils/message_bus/message_bus_client.py

- Implement MessageBus.init() as static instance
-  Remove MessageBus constructor and MessageBus() initialisation in MessageBusClient

EOS-27346: MessageBus as static instance

---

py-utils/README.md

Signed-off-by: Parayya Vastrad parayya.vastrad@seagate.com
- cortx-utils: Update Wiki page and README.md
-  https://jts.seagate.com/browse/EOS-27347
-----
[View rendered py-utils/README.md](https://github.com/vastradparayya/cortx-utils/blob/patch-2/py-utils/README.md)

EOS-27347: Update README.md

---

py-utils/src/utils/support_framework/support_bundle.yaml

Signed-off-by: Palak Garg <palak.garg@seagate.com>
- Add support for rgw support bundle in support bundle framework
- Added the support to invoke rgw support bundle from support bundle framework
- [] Is there a change in filename/package/module or signature [Y/N]:

EOS-28431: RGW support bundle integration with Support bundle Framework.

---

py-utils/src/support/cortx_support_bundle.py
py-utils/src/support/utils_support_bundle.py
py-utils/src/utils/const.py
py-utils/src/utils/setup/kafka/kafka_setup.py
py-utils/src/utils/support_framework/bundle_generate.py
py-utils/src/utils/utils_server/utils_server.py

- install_path and log_dir are not present in cluster_conf which breaks the operation

EOS-28487: support bundle logs fix

---

py-utils/src/utils/conf_store/conf_cli.py
py-utils/src/utils/conf_store/conf_store.py
py-utils/src/utils/kv_store/kv_store_collection.py
py-utils/test/conf_store/test_conf_store.py
py-utils/test/conf_store/test_conf_store_ini.py

Signed-off-by: Ujjwal Lanjewar <ujjwal.lanjewar@seagate.com>
- Fix for Conf.set in new section and Conf.copy to a blank file

EOS-28501: Fix INI section issue

---

py-utils/setup.py
py-utils/src/utils/http/__init__.py
py-utils/src/utils/http/client.py
py-utils/src/utils/http/exceptions.py
py-utils/src/utils/rgwadmin/__init__.py
py-utils/src/utils/rgwadmin/client.py
py-utils/src/utils/rgwadmin/examples/__init__.py
py-utils/src/utils/rgwadmin/examples/create_user.py
py-utils/src/utils/rgwadmin/exceptions.py

- [EOS-28023: Create BOTO like framework for communication between CEPH](https://jts.seagate.com/browse/EOS-28023)
-  [RADOSGW-ADMIN framework](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/888668545/RADOSGW-ADMIN+framework) 

EOS-28023: add RADOS Gateway client for Python

---

py-utils/src/utils/conf_store/conf_store.py
py-utils/test/conf_store/test_conf_store.py

- Added force option to delete
- https://jts.seagate.com/browse/CORTX-29256

CORTX-29256: resolution for non leaf key value deletion with force parameter

---

py-utils/src/utils/schema/release.py

CORTX-29406: Exceptions for RPM version check gives a general purpose error message instead being specific to the functionality.

---

py-utils/src/support/cortx_support_bundle.py

Signed-off-by: Palak Garg <palak.garg@seagate.com>
- Validation of required parameters need to be handled in cortx support bundle
- Adding the validations in cortx_support_bundle for required parameters

CORTX-29238: Validation of required parameters need to be handled in cortx support bundle

---

py-utils/src/utils/kv_store/kv_store_collection.py

- Fixed import failures.
-  Added import statements

CORTX-23443: Fix for imports fail

---

py-utils/src/utils/schema/database.py

Signed-off-by: Alexander Voronov <alexander.voronov@seagate.com>
- [CORTX-28033](https://jts.seagate.com/browse/CORTX-28033): Implement unsupported service feature for CSM
-  As a first step for CORTX-28033 it's decided to migrate the current implementation of unsupported features from ElasticSearch to Consul KVS.

CORTX-28033: migrate unsupported features from ElasticSearch to Consul

---

py-utils/src/support/cortx_support_bundle.py
py-utils/src/utils/kv_store/kv_payload.py
py-utils/test/conf_store/test_conf_store.py
py-utils/test/kv_store/test_kv_store.py

Merge Integration to sub-integration branch

---

.github/pull_request_template.md

- Updated PR template
-----
[View rendered .github/pull_request_template.md](https://github.com/Seagate/cortx-utils/blob/br/rahul/pr_temp_confkvstore/.github/pull_request_template.md)

CORTX-29610: Update PR template for conf/Kv store feature

---

py-utils/README.md

- Update Readme file for rocky linux
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  
-----
[View rendered …

CORTX-29951: Update Readme for Rocky linux

---

py-utils/python_requirements.txt

Signed-off-by: Swanand S Gadre <swanand.s.gadre@seagate.com>
Current cryptography version is 2.8. This version has High/medium level vulnerabilities
This version is planned to be upgraded to 3.3.2
Thought process of upgrading to version 3.3.2 is as follows
Version upgrade for cryptography library from version 2.8 to version 3.3.2 is recommended by Whitesource vulnerability scanning tool.
There are several cryptography versions available which are higher than 3.3.2. However further library package upgrade will be planned in subsequent iteration,
Reference to cryptography version to 3.3.2 is upgraded at following file
py-utils/python_requirements.txt
-  Coding …

CORTX-29993 - Update cryptography library from 2.8 to 3.3.2

---

py-utils/python_requirements.txt

- Upgrade cryptography from 2.8 to 3.3.2 

Upgrade cryptography from 2.8 to 3.3.2

---

py-utils/src/utils/schema/release.py

Signed-off-by: Kailash Yadav <kailash.yadav@seagate.com>
-  Implement Version compatibility logic.
- For example, current version: 10, new version: 12
if version 12 config allow transition to and from 10 and 11 version then version 10 is said to be compatible with version 12
-  https://jts.seagate.com/browse/CORTX-30806
- Confirm that Test Cases are …

CORTX-30806: Feature: Added version compatibility check

---

py-utils/setup.py
py-utils/src/utils/cleanup/es_data_cleanup.py
py-utils/src/utils/cli_framework/terminal.py
py-utils/src/utils/data/db/examples/elasticsearch_storage.py
py-utils/src/utils/data/db/generic_storage.py
py-utils/src/utils/ha/dm/decision_maker.py
py-utils/src/utils/ha/hac/generate.py
py-utils/src/utils/message_bus/message_broker_collection.py
py-utils/src/utils/process.py
py-utils/src/utils/schema/payload.py
py-utils/src/utils/setup/openldap/openldap.py
py-utils/src/utils/setup/openldap/setupReplication.py
py-utils/test/conf_store/test_conf_store.py

JIRA: [CORTX-31156](https://jts.seagate.com/browse/CORTX-31156)
LINK: [Codacy for PR](https://app.codacy.com/gh/Seagate/cortx-utils/commit?cid=639765691&fileBranchId=29020958)
- Critical codacy issues
-  fixed critical codacy issues
- Confirm Testing was performed with installed …

CORTX-31156: fix codacy issues

---

py-utils/src/utils/cortx/const.py

Signed-off-by: Tanuja Shinde <tanuja.shinde@seagate.com>
- CORTX-31277: add node_types in confstore to identify nodes in cortx
-  CORTX-31277: add node_types in confstore to identify nodes in cortx
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]: Y
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  Y

CORTX-31277: add node_types in cortx cnst.py to identify nodes in cortx

---

py-utils/python_requirements.txt

Signed-off-by: swanand-gadre <swanand.s.gadre@seagate.com>
Paramiko package 2.7.X is vulnerable.
It needs to be upgraded to version 2.10.4
This PR is raised to upgrade this version.
This PR is raised to upgrade paramiko package from 2.7.X to 2.10.4
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]: NA
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]: NA
- Confirm …

CORTX-30265 - paramiko upgrade to 2.10.4

---

py-utils/src/setup/utils.py
py-utils/src/setup/utils_setup.py
py-utils/src/utils/const.py

- Implement upgrade miniprovisioning phase
-  in utils, only kafka related keys are utilized in miniprovisioning, hence monitoring them and updating gconf accordingly

CORTX-29988: implement upgrade phase in miniprovisioning

---

py-utils/src/utils/event_framework/health.py

…f IO's.
HA k8s monitor service restart was observed because at some point of time
it failed at parsing the alert message because of some type mismatch. The
basic health event gets created using utils HealthEvent class. This event's
payload attribute "specific_info" has default value as 'str'. So, if
'set_specifc_info' gets called, then only, this value will change to 'dict'.
Otherwise it will remain as 'str' and the parsing will fail. So, This should be
dictionary as its purpose is to carry additional information in key value
format.
Signed-off-by: Madhura Mande <madhura.mande@seagate.com>
[- Problem statement ]
https://jts.seagate.com/browse/CORTX-31530
Make default value of "specific_info" of payload as dictionary
- …

CORTX-31530: Observed cortx-ha-k8s-monitor restart after ~115 hours of IO's

---

README.md
py-utils/README.md
py-utils/test/README.md

- Codacy warnings in Markdown files
-  Addressed 5 codacy warning in markdown 
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  
-----
[View rendered README.md](https://github.com/rohit-k-dwivedi/cortx-utils/blob/CORTX-31433/README.md)
[View rendered …

CORTX-31433: fix markdown codacy issue

---

py-utils/cortx.conf.sample
py-utils/src/utils/message_bus/message_broker_collection.py
py-utils/src/utils/message_bus/message_bus.py

Signed-off-by: Pawan Kumar Srivastava <pawan.kumarsrivastava@seagate.com>
https://jts.seagate.com/browse/CORTX-31536
- Control Pod occasionally hangs while running cortx-setup initContainer
-  For Bug describe the fix here. - 
- Making Kafka Server unavailable - 
- We deleted Kakfa server from deployment and then we performed the below steps - 
- We ran csm_setup phases (post_install, prepare, config (where it got stuck)
- During the config phase CSM tries to create a topic in Kafka. For that we use MessageBus interface from utils. 
- While initializing MessageBus we started receiving errors on console from Confluent Kafka python library.  But the code flow continued and did not hang.
- After that we called List Message Types of MessageBus interface and it internally calls list_topics …

CORTX-31536: Added timeout for list_topics to prevent Control POD from hanging

---

py-utils/src/utils/appliance_info/appliance.py
py-utils/src/utils/data/db/consul_db/storage.py
py-utils/src/utils/data/db/elasticsearch_db/storage.py
py-utils/src/utils/ha/hac/compile.py
py-utils/src/utils/ha/hac/generate.py
py-utils/src/utils/kv_store/kv_store_collection.py
py-utils/src/utils/schema/payload.py
py-utils/src/utils/setup/elasticsearch/elasticsearch_provisioner.py
py-utils/src/utils/setup/openldap/configcmd.py
py-utils/src/utils/setup/openldap/openldap.py
py-utils/src/utils/setup/openldap/test.py

Signed-off-by: rohit-k-dwivedi <rohit.k.dwivedi@seagate.com>
- unidiomatic-typecheck C0123
-  fixed type check be replacing `type(OBJ) == TYPE` to `isinstance(OBJ, TYPE)`
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  
https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/969573895/Activity+Codacy+Ba …

CORTX-32184: Fix codacy issue

---

py-utils/src/utils/support_framework/log_filters.py

Signed-off-by: rohit-k-dwivedi <rohit.k.dwivedi@seagate.com>
JIRA: [CORTX-33037](https://jts.seagate.com/browse/CORTX-33037)
-  `limit_time` filter API for Support bundle is capable to filter logs based on log timestamp format generated by utils logger
-   In earlier approach, to extract timestamp, the first 20 characters were used from the logline
`log_duration = line[:20].strip()` which then processes it as duration.
-   Now this duration is extracted using patterns from user supplied timestamp regex 
- Confirm that new test cases are added to regression and sanity plan files and relevant …

CORTX-33037: enhance support bundle time filter to accept different timestamp logs

---

py-utils/src/test_framework/README.md

- Py-utils: Update README.md for py-utils test_framework and tests
-  https://jts.seagate.com/browse/CORTX-29641
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]: NA
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]: NA
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: NA
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]: NA
-----
[View rendered …

Updating test_framework README.md file

---

py-utils/src/setup/utils.py
py-utils/src/utils/common/dbconf.py
py-utils/test/consul_service/test_consul.py

- Support fo Gconf migration to consul backend
-  Only leaf key allows get call for consul confstore backend.
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]: NA
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:NA
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: NA
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  Y

CORTX-32736: UTILS - Consul Support for GCONF

---

py-utils/src/utils/conf_store/conf_cache.py
py-utils/src/utils/conf_store/conf_store.py
py-utils/src/utils/const.py
py-utils/src/utils/kv_store/kv_store.py

Signed-off-by: Kailash Yadav <kailash.yadav@seagate.com>
-  Implement an interface to soft lock and unlock a config from Confstore, to avoid concurrent access and redundant effort from multiple config service instances.
-  [For Feature, Post the link to the solution page on the confluence CORTX Foundation Library ](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/1074626828/HLD+Distributed+Locks+using+Conf+Store)
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]:N
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:N
- Confirm that Test …

CORTX-32734_lock_interface: Conf store generic soft lock interface

---

.github/workflows/dispatch_submodule_update.yml

Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
- Fix submodule actions workflow as remove the 3rd party source repos due avoid rate-limit error as,
- Confirm Testing was performed with installed …

Fix submodule actions workflow

---

py-utils/README.md

- Codacy issue is reported for missing language name in a code section
-  Added Bash as language name
-  Coding conventions are followed and code is consistent [Y/N]: NA
-  Confirm All CODACY errors are resolved [Y/N]: NA
- Are test cases updated along with code changes due to Enhancements/Bugs [Y/N]:NA
- Confirm that new test cases are added to regression and sanity plan files and relevant feature plan files [Y/N]:NA
- Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability [Y/N]: NA
- Confirm Testing was performed with installed RPM/K8s deployment [Y/N]:  NA
-----
[View rendered py-utils/README.md](https://github.com/Seagate/cortx-utils/blob/CORTX-33 …

CORTX-33173: fixing Readme.md markdown file issue.

---

py-utils/src/utils/kv_store/kv_store_collection.py

- Conf.get for consul backend is first checking the built-in (cached) key_list, if the key is not present in cached key list, it is simply returning None. Now, if we load couple of consul conf indexes from two separate python kernels.  Then set a key:value from 1st index and try to fetch the value for the same key from 2nd index(which is on a separate python kernel), it wont be able to find the key in cached key_list and hence return None.
- This is as per current logic and it was done to reduce calls to consul KV over the network.
- The Logic for checking cached key_list is removed and now every get call is directly going to consul KV server to get the value.
- …

CORTX-33647: Confstore Consul backend should query consul while get.

---

CODEOWNERS

Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
- Added Codeowner to make Tanuja as the code owner for Utils repo

CORTX-33674: Added Codeowner

---

CODEOWNERS

CORTX-33819: Updating code owners 
